oshi/oshi

CHANGELOG.md
src/main/java/oshi/software/os/windows/nt/CentralProcessor.java
src/main/java/oshi/util/ExecutingCommand.java

Squashed commit:
[f8d2589] Code altered to suit more existing codebase (error management), added english localization flag to wmic command to prevent problems with parsing on non-english localized machines
[890ad66] CPU load implementation for windows
[39b933f] Added ability to read different than just first result line from command output (with proper sanitization) (+1 squashed commits)

CPU load implementation for windows

---

CHANGELOG.md
src/main/java/oshi/software/os/linux/proc/GlobalMemory.java
src/main/java/oshi/software/os/mac/local/GlobalMemory.java

Include inactive memory in mac/linux available.

---

CHANGELOG.md
src/main/java/oshi/hardware/HardwareAbstractionLayer.java
src/main/java/oshi/hardware/Memory.java
src/main/java/oshi/hardware/Processor.java
src/main/java/oshi/software/os/OperatingSystem.java
src/main/java/oshi/software/os/OperatingSystemVersion.java
src/main/java/oshi/software/os/Process.java
src/main/java/oshi/software/os/linux/Libc.java
src/main/java/oshi/software/os/linux/LinuxHardwareAbstractionLayer.java
src/main/java/oshi/software/os/linux/proc/CentralProcessor.java
src/main/java/oshi/software/os/linux/proc/GlobalMemory.java
src/main/java/oshi/software/os/mac/local/GlobalMemory.java
src/main/java/oshi/software/os/windows/WindowsHardwareAbstractionLayer.java
src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
src/main/java/oshi/software/os/windows/nt/CentralProcessor.java
src/main/java/oshi/software/os/windows/nt/GlobalMemory.java
src/main/java/oshi/software/os/windows/nt/OSNativeSystemInfo.java
src/main/java/oshi/software/os/windows/nt/OSVersionInfoEx.java
src/main/java/oshi/util/ExecutingCommand.java
src/main/java/oshi/util/FileUtil.java
src/main/java/oshi/util/FormatUtil.java
src/test/java/oshi/util/FileUtilTest.java
src/test/java/oshi/util/FormatUtilTest.java

Submitted for comment/discussion.  No feelings will be hurt if it's rejected. :)   Some comments:
- Only Linux function which is easily exposed to JNA is sysinfo, and that's really only good for Total ram.  You can also get Free ram from it, but as previously noted, that doesn't account for the true amount available.
- I tried various methods to get the other components of available.  I managed inactive using the meminfo() function (updates global variables) and then reading the kb_inactive global variable.  Unfortunately the necessary library for these was "libprocps.so.3".  I am not sure we should specify the version (version 4 may be out soon) and my system I set up as a testbed (Ubuntu 14.04 LTS) did not have a link from the non-versioned extension (so just plain "procps" didn't work …

Use sysinfo for linux total memory

---

.gitignore
CHANGELOG.md
src/main/java/oshi/hardware/Processor.java
src/main/java/oshi/software/os/linux/proc/CentralProcessor.java
src/main/java/oshi/software/os/mac/local/CentralProcessor.java
src/main/java/oshi/software/os/windows/nt/CentralProcessor.java
src/main/java/oshi/util/FormatUtil.java
src/main/java/oshi/util/ParseUtil.java
src/test/java/oshi/SystemInfoTest.java
src/test/java/oshi/util/FormatUtilTest.java
src/test/java/oshi/util/ParseUtilTest.java

Added the `getFreq` and `setFreq` methods to the `Processor` interface and for its implementations for Linux, Windows and Mac.

Support for processor frequency

---

CHANGELOG.md
pom.xml
src/assembly/assembly.xml
src/site/markdown/README.md
src/site/site.xml

~~License renamed so that expected license header can be used.~~ Completed on #48 
~~All license headers updated.  Similar to Waffle for the most part.~~ Completed on #49, #50, and Correct Assembly location here
~~Update to JNA 4.1.0 - added field order~~ Completed on #47 
~~Change assembly reference to license~~ Completed on #48 
Add bootstrapped site page
Maven Magic
Bring up-to-date with Waffle and/or simlar to my base-parent project
~~Upgraded to Java 1.7~~ Completd on #50

Bootstrap Site, Maven Magic, License Patch, Java 7

---

src/main/java/oshi/hardware/package-info.java
src/main/java/oshi/package-info.java
src/main/java/oshi/software/os/linux/package-info.java
src/main/java/oshi/software/os/linux/proc/package-info.java
src/main/java/oshi/software/os/mac/local/package-info.java
src/main/java/oshi/software/os/mac/package-info.java
src/main/java/oshi/software/os/package-info.java
src/main/java/oshi/software/os/windows/nt/package-info.java
src/main/java/oshi/software/os/windows/package-info.java
src/main/java/oshi/util/package-info.java
src/test/java/oshi/SystemInfoTest.java
src/test/java/oshi/util/FileUtilTest.java
src/test/java/oshi/util/FormatUtilTest.java
src/test/java/oshi/util/ParseUtilTest.java

Formatting is off a bit in a couple of places.  I missed setting spaces back to tabs.  However, I plan to do another pull sometime soon enforcing formatting which is space based and generally the accepted cross platform usage.  For now this is ok as these are at least aligned together in the right spaces.  Now everything have javadocs.

jautodoc remainder of non javadoc'd items.

---

src/main/java/oshi/software/os/windows/nt/OSVersionInfoEx.java

I erroneously replaced the return statement in my previous commit.
Thus, additional SP may be appended to NT4 SP6a and it should not.

immediate return for "NT4 SP6a" to prevent additional SP to be appended

---

CHANGELOG.md
src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
src/main/java/oshi/hardware/platform/linux/LinuxGlobalMemory.java

Use /proc/meminfo as fallback to sysinfo to remove glibc dependence

---

CHANGELOG.md
README.md
src/main/java/oshi/hardware/HardwareAbstractionLayer.java
src/main/java/oshi/hardware/Sensors.java
src/main/java/oshi/hardware/platform/linux/LinuxHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/linux/LinuxSensors.java
src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
src/main/java/oshi/hardware/platform/mac/MacHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/mac/MacSensors.java
src/main/java/oshi/hardware/platform/windows/WindowsHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/windows/WindowsSensors.java
src/main/java/oshi/jna/platform/mac/CoreFoundation.java
src/main/java/oshi/jna/platform/mac/IOKit.java
src/main/java/oshi/jna/platform/mac/SystemB.java
src/test/java/oshi/SystemInfoTest.java

OS X and Linux CPU temperature and fan speeds for #119

CPU temperature, fan speeds, and voltage

---

src/main/java/oshi/hardware/platform/linux/LinuxDisplay.java

+ NullPointer control when OS doesn't have command xrandr when try to iterate over null value.
+ Controll over null value in foreach.

FIX: NullPointer when try to extract display

---

src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

+ avoid NullPointer exception with default value in false in cpu64 attribute in LinuxCentralProcessor
issue #131

FIX: initialize cpu64 attribute in false by default

---

CHANGELOG.md
src/main/java/oshi/hardware/CentralProcessor.java
src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
src/main/java/oshi/jna/platform/linux/Libc.java

With this pull request, for getting the CPU Load average is used the Linux proc file as fallback of the native Java method

Modified method for getting CPU load average

---

CHANGELOG.md
src/main/java/oshi/software/os/OSFileStore.java
src/main/java/oshi/software/os/linux/LinuxFileSystem.java

Another two things:
- I'm not sure if `store.name()` can be replaced if `path` equals "/"
- Why informations are fetched from `/proc/self/mounts` and ` FileSystems.getDefault().getFileStores()` ?

Reviewing getFileStores() method

---

CHANGELOG.md
src/main/java/oshi/hardware/platform/mac/MacDisplay.java

Looping over the different children of IODisplayConnect nodes did not work. Only the first one was returned, because the value given to IOIteratorNext in the while loop was wrong.

Fix reading multiple (external) displays on Macs

---

.travis.yml
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java

Don't double-release enumerator on failed WMI query.

---

oshi-core/src/test/java/oshi/util/ExecutingCommandTest.java

Rationale: this test doesn't work on Windows because `echo` is an internal command of cmd.exe

Fixed test in Windows environment

---

.gitignore
CHANGELOG.md
oshi-core/src/main/java/oshi/jna/platform/linux/Libc.java
oshi-core/src/main/java/oshi/jna/platform/mac/SystemB.java
oshi-core/src/main/java/oshi/software/common/AbstractProcess.java
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxProcess.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSVersionInfoEx.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacProcess.java
oshi-core/src/main/java/oshi/util/FileUtil.java
oshi-core/src/test/java/oshi/util/FileUtilTest.java
oshi-core/src/test/resources/test.procio.txt
oshi-dist/pom.xml
oshi-json/src/main/java/oshi/json/software/os/OSProcess.java
oshi-json/src/main/java/oshi/json/software/os/impl/OSProcessImpl.java
oshi-json/src/test/resources/oshi.json.properties

Summary:
This change adds bytesRead and bytesWritten fields to OSProcess.
An implementation is provided for MacProcess which uses `proc_pid_rusage(pid, RUSAGE_INFO_V2, ...)`.
Note that RUSAGE_INFO_V2 is only available on MacOSX 10.9+.
Test Plan:
Successfully obtained process io stats on MacOSX 10.10 and 10.11.
Verified that `mvn test` succeeds.

[OSHI] Add bytesRead and bytesWritten to OSProcess

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxBlockDevStats.java

Hello,
These changes contain bugfix for Linux block device stats. See issue #268 for more details and conversation about implemented changes. `mvn clean test` completed without errors.
Regards,
lu-ko

Fix Linux blockdevstats on some distributions

---

oshi-core/pom.xml
oshi-core/src/site/site.xml
oshi-dist/pom.xml
oshi-dist/src/assembly/assembly.xml
oshi-dist/src/main/resources/eclipse/format.xml
oshi-dist/src/site/site.xml
oshi-json/pom.xml
oshi-json/src/site/site.xml
oshi-json/src/test/resources/oshi.json.properties
pom.xml
src/site/site.xml

Site.xml should exist in every module folder otherwise it doesn't properly build individually for local usage.
License setup was originally just copied from the plugin website.  That was wrong as it was  sample and limited it to only the java files.  Fixed that and adjusted it so it doesn't affect what is considered simply test files that shouldn't have headers.

Site and License adjustments

---

README.md

It is not very straight forward to run the advertised `SystemInfoTest` from the command line unless one is eager to download a few jars and add them to the classpath (SLF4J, JNI, JSON).
For people familiar with **Git** and **Maven**, running a mvn command to execute `SystemInfoTest` will require less effort ...and if included in the README it comes down to a simple copy and paste :smile:
```Bash
mvn test-compile -pl oshi-core -q exec:java \
-Dexec.mainClass="oshi.SystemInfoTest" \
-Dexec.classpathScope="test"
```

Include instructions to run SystemInfoTest

---

oshi-core/src/test/resources/simplelogger.properties
oshi-json/src/test/resources/simplelogger.properties

Fix for issue #299
**Proposed change**
- capture log messages in log file `**/target/unit-tests.log` instead of mixing them in with surefire console output
- don't log _expected_ errors and warning from `oshi.util.*` and `oshi.json.util.*` during test execution
**How was this change tested**
- ran full maven build and test build, verified log files get created and are empty
- captured STDOUT and STDERR separately make sure undesired log messages are no longer in the build output
- temporarily added log statements into test source code to verify output was captured in the modules respective log file `**/target/unit-tests.log`

Fix #299: Suppress expected WARN and ERROR messages during Maven test build

---

CHANGELOG.md
oshi-core/src/main/java/oshi/jna/platform/linux/Libc.java
oshi-core/src/main/java/oshi/jna/platform/unix/LibC.java
oshi-core/src/main/java/oshi/jna/platform/windows/IPHlpAPI.java
oshi-core/src/main/java/oshi/jna/platform/windows/Kernel32.java
oshi-core/src/main/java/oshi/software/common/AbstractNetworkParams.java
oshi-core/src/main/java/oshi/software/os/NetworkParams.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxNetworkParams.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacNetworkParams.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdNetworkParams.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisNetworkParams.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsNetworkParams.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/software/os/NetworkParamsTest.java
oshi-json/src/main/java/oshi/json/software/os/NetworkParams.java
oshi-json/src/main/java/oshi/json/software/os/OperatingSystem.java
oshi-json/src/main/java/oshi/json/software/os/impl/NetworkParamsImpl.java
oshi-json/src/main/java/oshi/json/software/os/impl/NetworkPramsImpl.java
oshi-json/src/main/java/oshi/json/software/os/impl/OperatingSystemImpl.java
oshi-json/src/test/java/oshi/json/SystemInfoTest.java
oshi-json/src/test/java/oshi/json/software/os/NetworkParamsTest.java
oshi-json/src/test/resources/oshi.json.properties

Hi,
here is interface for OS networking parameters and implementation for Linux/Win (sorry I don't have machine for other OS :().
Now it contains host name/dns domain name/dns servers/default gateway of IPv4/6.
Domain suffix search list is also considered but I think I'll wait JNA release `VT_ARRAY` support for this.

Host/domain name, dns servers and default gateways information for Win/Linux

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/ComputerSystem.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsComputerSystem.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/hardware/CentralProcessorTest.java
oshi-json/src/main/java/oshi/json/hardware/CentralProcessor.java
oshi-json/src/main/java/oshi/json/hardware/impl/CentralProcessorImpl.java
oshi-json/src/test/java/oshi/json/SystemInfoTest.java
oshi-json/src/test/java/oshi/json/hardware/CentralProcessorTest.java

It duplicated ComputerSystem's getSerialNumber method.  See #296

Deprecate CentralProcessor's getSystemSerialNumber method

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

when logical processors are detected but no physical one, you can
safely assume there is at least one physical cpu.
This case happens on virtual machines where there is in cpuinfo only
"processor" lines.
Example:
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 62
model name      : Intel(R) Xeon(R) CPU E5-2640 v2 @ 2.00GHz
stepping        : 4
microcode       : 0x427
cpu MHz         : 2000.000
cache size      : 20480 KB
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge
mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx rdtscp
lm constant_tsc arch_perfmon pebs bts nopl xtopology tsc_reliable
nonstop_tsc aperfmperf pni pclmulqdq ssse3 …

Fixed physical processor count fallback

---

oshi-core/src/test/java/oshi/hardware/DisksTest.java
oshi-json/src/test/java/oshi/json/hardware/DisksTest.java

Changed the disk size check to -1 to handle SD card readers that are detected, but not mounted, and therefore have a size of 0.

DisksTest minor update

---

CHANGELOG.md
pom.xml

I would be very useful if the oshi jar distribution would contain the necessary headers for OSGi environments. 
I made some changes to the maven pom that pulls in the bnd maven plugin which automatically adds this headers to the oshi-core and oshi-json project. I have also added some headers to the maven source plugin  so the source jar can also be used in OSGi environments as a "Source Bundle".

Added OSGi Support

---

oshi-core/src/main/java/oshi/hardware/platform/mac/MacDisks.java

The conversion from nanoseconds 10 ^ -9 to milliseconds 10 ^ -3 should
be division by 1,000,000 not 10,000.

Nanoseconds to Milliseconds

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java

of the buffer into which it can copy, not the number of elements.

Fixes #395 the forth parameter to proc_listpids() is the size

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

When initializing LinuxOperatingSystem class, a lookup
is done through PID files to find the more recent one
However some processes may have been already killed
between the PID list is obtained and the time the PID
files are accessed
So explicitly say that no error should be printed when
this happens

No warning when PID file is no longer avail

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Added validation on use of fields that might be zero after initialization error for the LinuxOperatingSystem class

Add validation for uninitialized fields in LinuxOperatingSystem

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworks.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

This fixes a widening conversion issue in `WindowsNetworks` where improper mask of 7 `f` digits instead of 8 is used. This was discussed in #333 and @dbwiddis suggested moving the unsigned int to long conversion to an utility method in `ParseUtil`.

Fix for wrong unsigned int to long widening in WindowsNetworks

---

oshi-core/src/main/java/oshi/util/EdidUtil.java
oshi-core/src/test/java/oshi/util/EdidUtilTest.java

This Pull Request addresses issue #450 
Fixes wrong reading of Digital/Analog detection method EdidUtil#isDigital 
Fixes wrong reading of active resolution detection method EdidUtil#getTimingDescriptor
Before:
```
Checking Displays...
Displays:
Display 0:
Manuf. ID=ACB, Product ID=216, Analog, Serial=110ￓ0E, ManufDate=4/2011, EDID v1.3
53 x 30 cm (20,9 x 11,8 in)
Preferred Timing: Clock 148MHz, Active Pixels 3840x1920 
Range Limits: Field Rate 56-76 Hz vertical, 31-83 Hz horizontal, Max clock: 170 MHz
Monitor Name: S242HL
Serial Number: LR90D0048570
Display 1:
Manuf. ID=DEL, Product ID=a097, Analog, Serial=3MWS, ManufDate=12/2014, EDID v1.4
48 x 27 cm (18,9 x 10,6 in)
Preferred Timing: Clock 148MHz, Active Pixels 3840x1920 
Serial Number: 29C294BO3MWS
Monitor Name: DELL P2214H
Range …
```

Fixes for issue 450

---

oshi-core-shaded/pom.xml
pom.xml

This is also needed for Payara because SLF4J isn't OSGi compliant,
This deploys an additional -shaded JAR that includes the transitive dependencies

Shaded jar that includes it's dependencies for Oshi core

---

oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/test/java/oshi/hardware/CentralProcessorTest.java
oshi-json/src/main/java/oshi/json/hardware/CentralProcessor.java
oshi-json/src/main/java/oshi/json/hardware/impl/CentralProcessorImpl.java
oshi-json/src/test/java/oshi/json/hardware/CentralProcessorTest.java

Add 2 methods in CentralProcessor interface
only Linux implementation provided for now

Add context switches & interrupts

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworks.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

#440:
Multiplied the network speed by 2^20 to normalize it from MiBs to Bytes.
Also added an overflow check (It shouldn't ever happen though, as that would mean network speeds above 7 Exabytes per second)
#442:
Instead of building a whole new method inside a util class to allow for the correct **/proc/[PID]/stat** file parsing (where the first two delimiters are " (" and ") ", instead of whitespaces), I just used the current file splitting, then concatenated any resulting token that belonged to the **name** field.

Fix Linux OS issues: #440 and #442

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

Use correct type for Linux processor dmidecode

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/util/platform/windows/PdhUtil.java
oshi-core/src/test/java/oshi/SystemInfoTest.java

Committing the PdhUtil and intial implementation for CentralProcessor.  Further implementations will come in later PRs.

Replace WMI with PDH for WindowsCentralProcessor counters

---

oshi-core/src/main/java/oshi/software/os/FileSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java

Return Windows Handle Count instead of 0 for File Descriptor counts.

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

For the most part command line retrieval appears to be broken under Windows. When investigating the issue, I found that process caching also appears a bit suspect, so I tweaked that logic a bit as well. Since the changes are concise, I'll let the diff speak for the details.

Correct process information caching and command line retrieval under Windows

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

… to an empty cache
The empty cache caused an empty process list.

Disabled Windows performance collection leads to empty Process cache

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisplay.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdDisplay.java

It seems that the constructor was not updated when copying
SolarisDisplay to FreeBsdDisplay and LinuxDisplay.

Fix wrong constructor call in FreeBsdDisplay and LinuxDisplay.

---

oshi-core/src/main/java/oshi/hardware/common/AbstractNetworks.java

Moving the try/catch into the loop body ensures every interface is given
a chance.
Also this change makes it possible to alter
NetworkIF.setNetworkInterface to throw SocketException rather than
consuming it. Since that method is technically part of the API (although
it shouldn't be), I didn't mess with it.

Prevent skipped interfaces in the event of a SocketException.

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java
oshi-core/src/main/java/oshi/jna/platform/windows/Cfgmgr32.java
oshi-core/src/main/java/oshi/jna/platform/windows/Cfgmgr32Util.java
oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java

Fixes #566 . Completely eliminates WMI queries when there's no change in USB devices, reducing average repeat USB device retrieval time from 1.9 seconds to 1.5 milliseconds.

Cache USB Devices

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java
oshi-core/src/main/java/oshi/util/ExecutingCommand.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java

Fix Windows interrupt count bug.

---

oshi-core-shaded/pom.xml
pom.xml

Due to the change in https://github.com/oshi/oshi/pull/464 by @lprimak some OSGi imports where missing. I have readded them and deliberately made com.sun.management optional because in some OSGi environments this API is not exposed on default. oshi can be used without this package being imported as we can see in https://github.com/oshi/oshi/blob/master/oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java there is a graceful fallback when "com.sun.management.OperatingSystemMXBean" can't be used.

OSGi imports missing

---

oshi-core/src/main/java/oshi/util/platform/windows/PerfDataUtil.java

Make sure that the **PdhQuery** is not null before closing it in the _removeAllCounters()_ method.
This behavior can happen when the **PdhCounter** retrieval fails on the first counter: the **PdhQuery** was never opened/added to the _queryMap_ in the first place.

#632 removeAllCounters() - Null query check

---

.travis.yml
CHANGELOG.md
oshi-core/src/main/java/oshi/jna/platform/linux/Libc.java
oshi-core/src/main/java/oshi/software/os/OSFileStore.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisFileSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/software/os/FileSystemTest.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java
oshi-json/src/main/java/oshi/json/software/os/OSFileStore.java
oshi-json/src/main/java/oshi/json/software/os/impl/FileSystemImpl.java
pom.xml

Hi,
initial pull request ... not sure about the variable names ... in LibC I have called them (free|total)InodeCounts because that's what it  is (at least on Linux) ... not sure if it's called like that for all the other OS as well. In FreeBSD it's called
> file serial numbers (i.e., inodes)
But in LinuxFileSystem I have called them file counts ... let me know what you prefer. Furthermore I had issues using the "new" JNA stuff ... if you convert the existing Sysinfo I can adapt Statvfs as well.
Furthermore I have set it to -1 for all other OS except of Linux ... not sure how to implement it for FreeBSD, Solaris, MacOS, ...

Add free/total inode counts

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/Util.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/util/UtilTest.java

Followed instructions here https://github.com/oshi/oshi/issues/648#issuecomment-441328862 . I also made a small change to SystemInfoTest.java for a good test. I hope that's OK. If not, I can roll that change back.
In addition to the code provided, I added a check using manufacturer and model for Microsoft Hyper-V VMs. I noticed that the Mac address and model check isn't enough for a VM I use for work, but manufacture and model check took care of that.
Thanks and let me know your comments/suggestions!

Check for Virtual Machine

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Refactored unsigned long bitmasking by extracting bitmasking logic to a utility method. Resolves #723

Refactored unsigned long bitmasking

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsSensors.java
oshi-core/src/main/java/oshi/jna/platform/windows/Kernel32.java
oshi-core/src/main/java/oshi/jna/platform/windows/VersionHelpers.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/java/oshi/util/platform/windows/PdhUtilXP.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfDataUtil.java
oshi-core/src/main/java/oshi/util/platform/windows/WmiQueryHandler.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java
oshi-core/src/test/java/oshi/util/UtilTest.java
oshi-json/src/test/java/oshi/json/software/os/OperatingSystemTest.java

Windows XP Compatibility Fixes

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java

The implementation for Windows Disk transfer time subtracted idle time from a timestamp.  While this properly incremented and allowed differential measurement, the overall counter value was nonsensical.   There's no reason not to directly measure the % Disk Time counter....

Fix Disk transfer time counters

---

oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/jna/platform/windows/Kernel32Util.java
oshi-core/src/main/java/oshi/jna/platform/windows/ProcInfo.java
oshi-core/src/main/java/oshi/jna/platform/windows/WinNT.java

The union embedded in SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX has a
dynamic size. So at decoding time the size depends on the Relationship
code embedded in the structure.
Instead of trying to press this through the default JNA union 
deserialization, model the four cases created by the four embedded
structures in the dummy union as separate subclasses of 
SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX.
Implementation provided by @matthiasblaesing

Handle SYSTEM_LOGICAL_PROCESSOR_INFORMATION_EX union as subclassing

---

oshi-core/src/main/java/oshi/util/Util.java
oshi-core/src/test/java/oshi/util/UtilTest.java

This pull request does not fully fix https://github.com/oshi/oshi/issues/796, there are many places where System.currentTimeMillis is used to measure time intervals, e.g. the MacNetworks.mapIFs method.

Reinstate the interruption status in Util.sleep and remove the unused Util.sleepAfter

---

README.md

Thanks a lot for the very good library!
The [Eclipse Passage](https://projects.eclipse.org/projects/technology.passage) project (open source license management solution) started to use OSHI last year to support node-locked licensing story.
[Recently](https://download.eclipse.org/tools/orbit/downloads/drops/I20190221153854/) oshi-core 3.8.0 has been added to [Eclipse Orbit](https://projects.eclipse.org/projects/tools.orbit) to be available for other Eclipse projects. This version has been selected to simplify the process, as required libraries for this version were already there.
I'm planning to upgrade it to more recent version but may need your advice.
Thanks again,
AF

Mention Eclipse Passage and Eclipse Orbit

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java

On LinuxFileSystem
In case, can't use statvfs.
example(when using docker) ------------------------------
overlay /var/lib/docker/overlay2/b0507253e8d99affaee4d98aedd2e63c498d35f8935f39a5a548e4ad29370d28/merged overlay rw,relatime,lowerdir=/var/lib/docker/overlay2/l/RR5VM6KYGW2QR635AT6PD3W3OZ:/var/lib/docker/overlay2/l/RGAWXHIO3SAE4ZXG6HDTYNF35F:/var/lib/docker/overlay2/l/DV57K6JHTFAWWTLEE3AQDDC5BM:/var/lib/docker/overlay2/l/TCFABWTRK6SNIBB5EPDD34S3KE:/var/lib/docker/overlay2/l/AGUVZWBFSBXBZXBMNFYKJSA7HN:/var/lib/docker/overlay2/l/HCXC3JZZBVZHXUODIELS6KCV7J:/var/lib/docker/overlay2/l/U4E757CTDIVOUBSC6TIM74ZIF5:/var/lib/docker/overlay2/l/RK67XYMJQBCKBT5BR7EFJ263JN:/var/lib/docker/overlay2/l/NVAOGWX7RZ2355F7GAPGMZTGJD:/var/lib/docker/overlay2/l/MKWME6JXDSOQWSRQS3GKY7GKUW:/var/lib/docker/overl …

Change log level when fail to use statvfs

---

appveyor.yml

Closes #881. This configuration doesn't calculate code coverage or anything fancy since Travis is already doing that.
Getting AppVeyor to build the repo is basically the same process as Travis.

Introduce AppVeyor CI

---

appveyor.yml

I wasn't able to get the connection to fail on my fork, but this should retry three times if any artifacts fail to download during the build.

Retry mvn-clean-package if failure

---

pom.xml

overrides are no longer necessary in last few revisions as maven has caught up entirely.
note: some overrides / inclusions as noted are necessary but the others were no longer needed.  While one could debate overriding jgit, the fact is that we are building with jdk8+ and maven is still stuck on jdk7 version.  Jgit no longer supports jdk less than 8.

[pom] Cleanup scm plugin usage

---

pom.xml

- Override is no longer necessary as spotbugs maven plugin is released often now.
- Adjusted settings to get slightly more items marked (3 in this case).
- Add spotbugs to check profile so that it executes there.

[pom] Reconfigure spotbugs-maven-plugin and update to 3.1.12.2

---

.travis.yml

All jdks will be auto pulled via normal procedure now.  The install-jdk is part of travis by default.  For the xcode 9.3, that one will remain with jdk not set and thus will use what is on the vm (oracle jdk 8).

Retool the travis ci jdk selection process

---

oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/resources/simplelogger.properties
pom.xml

Fixes #829 
The overall class is great for testing with oshi.  This class has become a baseline for [psi-probe](https://github.com/psi-probe/psi-probe/blob/master/core/src/main/java/psiprobe/controllers/oshi/OshiController.java).  In order to allow for easier porting of changes over to psi-probe, the structure needs to better adhere to accepted java standards such as not using system out printing.  Further, in this case, psi probe wants to show the results on a webpage rather than logging.  While Oshi did a little bit of both using a logger and system out printing, some slight adjustments and use of an array list result in similar outcome.  Essentially, outside of psi probe usage of setting up a controller, the port will mostly be intack same code without the current merge conflict …

Rework SystemInfoTest for Better Usability (Fixes #829)

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/HWDiskStore.java
oshi-core/src/main/java/oshi/hardware/HWPartition.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/hardware/DisksTest.java

HWDiskStore & HWPartition toString Methods for #942

Add toString methods to disk and partition API 

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

Added OSProcess constructor with PID (#957)

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

Microsoft docs say not to use [`HKEY_PERFORMANCE_DATA`](https://docs.microsoft.com/en-us/windows/win32/perfctrs/using-the-registry-functions-to-consume-counter-data)
> You can use the registry functions to collect performance data. However, the performance data is not actually stored in the registry database. Instead, calling the registry functions causes the system to collect the data from the appropriate performance counter provider.
>
>You should not use the registry functions to consume counter data. Instead, you should use the Performance Data Helper (PDH) functions to consume counter data. The PDH functions are easier to use, oriented more towards operations on single counters rather than groups of counters, and can be used to access counter data from current activity or log files. …

Replace registry Performance Data with PDH

---

CHANGELOG.md
oshi-core/pom.xml
oshi-core/src/main/java/oshi/jna/platform/linux/LinuxLibc.java
oshi-core/src/main/java/oshi/jna/platform/mac/SystemB.java
oshi-core/src/main/java/oshi/jna/platform/unix/CLibrary.java
oshi-core/src/main/java/oshi/jna/platform/unix/freebsd/FreeBsdLibc.java
oshi-core/src/main/java/oshi/jna/platform/unix/solaris/SolarisLibc.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxNetworkParams.java
oshi-core/src/main/java/oshi/software/os/mac/MacNetworkParams.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdNetworkParams.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisNetworkParams.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsNetworkParams.java

Fixes #1006
on windows, getHostName() uses Kernel32Util.getComputerName().
and on Mac, Linux, Solaris, and BSD it returns the value from JNA's LibC class method getHostName().
I have a question. [contributing guide](https://github.com/oshi/oshi/blob/master/CONTRIBUTING.md#update-changelog-again) says "Update CHANGELOG Again" and I'm somewhat confused. Do I have to update changelog at the moment I made a pull request or when my pull request got merged?

Specialize getHostName()

---

CHANGELOG.md
FAQ.md
oshi-core/src/main/java/oshi/hardware/GlobalMemory.java
oshi-core/src/main/java/oshi/hardware/PhysicalMemory.java
oshi-core/src/main/java/oshi/hardware/common/AbstractGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGlobalMemory.java
oshi-core/src/main/java/oshi/util/FormatUtil.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/SystemInfoTest.java

Physical memory additional information implementation

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Puts back in faster code removed in #1001, preferred to WMI for the case when PDH counters are disabled.  See #1029 for discussion.

Read HKEY_PERFORMANCE_DATA for process counters if possible

---

CHANGELOG.md
oshi-core/src/main/java/oshi/jna/platform/linux/LinuxLibc.java
oshi-core/src/main/java/oshi/jna/platform/windows/Kernel32.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/SystemInfoTest.java

Process affinity implementation

---

README.md

The repository has been restructured so the link needs to be updated.

Fix broken "openHAB Systeminfo Binding" link

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/test/java/oshi/hardware/NetworksTest.java

First time PR.
Adds Subnet Mask and Prefix Length to the NetworkIF.
This was one of the problems addressed in #696 
If there is interest, I also have something which can read most of the other problems defined in the issue. This code is, however, Linux specific, as it uses the corresponding interface files.

Subnet Mask & Prefix Length

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java

Hi,
first try at pull request. It compiles fine and uses 1 - %IdleTime to set the TransferTime.
Can you test this? I switched my system to Linux and don't have a test system at hand right now.
Thanks, Space

#1061 Fix transferTime in WindowsDisks by using 1-%Idle

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java

Fix issue with transfertime. Basically the only thing incorrect was that the xferTimeMap was using "% disk time" and not "% idle time". But to make it more clear I renamed it to idleTimeMap.
Please verify on your Windows system as well! Thanks and best regards, Space

#1061 Feature/windows transfertime 3.13.x

---

oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Allow nonnumeric strings at end of proc arrays

---

CHANGELOG.md
oshi-demo/src/main/java/oshi/demo/OshiHTTPServer.java

[oshi-demo] Vend JSON via HTTP Server

---

oshi-core/src/main/java/oshi/hardware/common/AbstractNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdDisks.java

Disk and Network method performance and thread safety

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32LogicalDisk.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java

Fix Windows FileStore updating

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworks.java
oshi-core/src/main/resources/oshi.vmmacaddr.properties
oshi-core/src/test/java/oshi/hardware/NetworksTest.java
oshi-demo/src/main/java/oshi/demo/DetectVM.java
oshi-demo/src/main/java/oshi/demo/gui/package-info.java
oshi-demo/src/main/java/oshi/demo/package-info.java

Add fields to NetworkIF to help determine physical interfaces

---

oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

- set initial 'state' of OSProcess instance as 'null' to detect OSProcess instance that does not reflect real process information
- Change testing of 'os.getParentProcessID()' to see whether it points real process id
- Change testing of 'proc.getBitness()' to rigorously check its condition (32 or 64 bit)

minor correction for catching future fault

---

oshi-core/src/main/java/oshi/driver/unix/NetStatTcp.java
oshi-core/src/main/java/oshi/software/os/mac/MacInternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdInternetProtocolStats.java

Fix #1200
- Create`NetStatTcp` class with `queryTcpnetstat()` method
- Delete repeated methods in `MacInternetProtocolStats.java` and `FreeBsdInternetProtocolStats.java`

Refactor duplicated queryTcpnetstat method

---

CHANGELOG.md

The project was started by @dblock, and a few years ago, we switched to the @oshi organization. #880 tried to remove all references to the old links, but missed the changelog!
So I Searched and replaced all links of the form https://github.com/dblock/oshi/pull to read https://github.com/oshi/oshi/pull.

Fix : fixed the broken links in CHANGELOG.MD

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxVirtualMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisVirtualMemory.java

-Change Linux virtual memory to use pswpin and pswap out instead of pgpgin and pgpgout.
-Change Solaris virtual memory to use pgswpin and pgswap out instead of pgpgin and pgpgout.
As requested in #1223

Change linux swapin/swapout counters to read only swaps

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxVirtualMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisVirtualMemory.java

-Change Linux virtual memory to use pswpin and pswap out instead of pgpgin and pgpgout.
-Change Solaris virtual memory to use pgswpin and pgswap out instead of pgpgin and pgpgout.
Cherry-picked from roeezz-linux-swp

Change linux swapin/swapout counters

---

CHANGELOG.md
FAQ.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/MemoryInformation.java
oshi-core/src/main/java/oshi/driver/windows/perfmon/PagingFile.java
oshi-core/src/main/java/oshi/driver/windows/perfmon/PhysicalDisk.java
oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessInformation.java
oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessorInformation.java
oshi-core/src/main/java/oshi/driver/windows/perfmon/SystemInformation.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterQuery.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterQueryHandler.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java
oshi-core/src/test/java/oshi/SourceCodeTest.java
pom.xml

Refactor PerfCounterQuery classes and fix memory leak

---

oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java

This fix will work for single element arrays, but not for multi-element arrays I think.
Am I supposed to only manipulate the String builder part? One solution I thought would be to combine the two arrays when they are being initially fed values, but that would mean only 2 arrays remain instead of current 4.

Outputs for IPv4 & subnetMask and IPv6 & prefix lengths combined

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/resources/oshi.linux.filename.properties

Hello @dbwiddis 
I am trying to address the issue you pointed here ([#1264](https://github.com/oshi/oshi/issues/1264#issuecomment-646229626))
moved cases from  LinuxOperatingSystem.filenameToFamily() to oshi.linux.filename.properties
I will update the changelog file if there is nothing more to change here.

Moved cases from function to properties

---

CHANGELOG.md
oshi-demo/src/main/java/oshi/demo/DiskStoreForPath.java

Demo class matching filestore to partition

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/resources/oshi.windows.versions.properties

Hello Daniel(@dbwiddis),
I moved the windows version names from WindowsOperatingSystem.parseVersion to the properties file, oshi.windows.versions.properties. 
Please review my changes and let me know if anything needs to updated or even a changelog updation is required.
Thanks.

Moved windows version parsing logic to a properties file

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/Lshw.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxFirmware.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/resources/oshi.properties

Use lshw as backup for max CPU frequency

---

FAQ.md
README.md
RELEASING.md
UPGRADING.md
oshi-core/src/main/java/oshi/driver/mac/net/NetStat.java
oshi-core/src/main/java/oshi/hardware/Sensors.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/java/oshi/util/FormatUtil.java

Updated some links to https for more secure connections :sunglasses:
* Note: The link to ``nd4j.org`` is dead; you may want to remove it

Updated links in the docs to https

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/ExecutingCommand.java

Closes #1347 
Passes locale when executing commands on different platforms.

Passes default locale setting when executing commands.

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java

Basically copied from you comment.....
Seems kinda hacky to get a PR that way.....

Logical cores iteration

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java

Retrieve process name and state from stat string if status map doesn't contain them already.
(I checked for Uid and Gid too, but it seems they are not contained in the string)

Backup for process name and state

---

CHANGELOG.md
oshi-core/src/main/resources/oshi.properties

This will result in [SquashFS](https://nl.wikipedia.org/wiki/SquashFS) filesystems - which are read-only by design - being hidden by default from `os.getFileSystem().getFileStores()`
Ubuntu snaps generate a lot of these when you have some snaps installed
close #1378

Add `squashfs` as a pseudo file system so it will be skipped by default

---

oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Adds assert messages to `ParseUtilTest#testParseStringToLongArray`.
Might have an opportunity to add some assertions to the other uncovered methods in this class.
Fixes #1215

Adds assert messages to a method in ParseUtilTest

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

Fix for WindowsOperatingSystem.getChildProcesses throwing exception, trying to sort unmodifiableList:
java.lang.UnsupportedOperationException
at java.util.Collections$UnmodifiableList.sort(Collections.java:1331)
at oshi.software.common.AbstractOperatingSystem.processSort(AbstractOperatingSystem.java:155)
at oshi.software.os.windows.WindowsOperatingSystem.getChildProcesses(WindowsOperatingSystem.java:296)

Fix exception sorting child process list on Windows

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

I was getting error on maven test:
[ERROR] oshi.software.os.OperatingSystemTest.testGetServices  Time elapsed: 0.443 s  <<< FAILURE!
java.lang.AssertionError: 
There should be at least 1 stopped service
Expected: is a value greater than <0>
but: <0> was equal to <0>
at oshi.software.os.OperatingSystemTest.testGetServices(OperatingSystemTest.java:339)
and found out that getServices() in LinuxOperatingSystem class was trying to get current list of services from systemd assuming that systemctl list-unit-files returns just two columns of data while on my version (systemd 246 (246.6-1-arch)) it returns 3 columns: " 'UNIT FILE'          'STATE'           'VENDOR PRESET' ", so I updated that function so it will handle 3 columns, and after my small change it seems to work good now, maven test …

support systemctl list-unit-files return 3 columns

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

Parse processor name on Orange Pi

---

pom.xml

This ties to the maven settings file.  Using a different name on both would require duplicate entries for the account data.  The suggested entry at least check (few years) was to call it ossrh.  Either way, its duplicate settings or consistent name.  Please do make sure to adjust your local as well.  In fact, there makes sense to have duplicate entries for all 3 (2 original plus this) as many teams use various older setups.

[pom] Use suggested sonatype id as 'ossrh' for both

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/resources/oshi.macos.versions.properties

Fix macOS codename with new versioning scheme

---

CHANGELOG.md
oshi-core-shaded/pom.xml
oshi-core/pom.xml
oshi-core/src/main/java/oshi/driver/linux/proc/ProcessStat.java
oshi-core/src/main/java/oshi/driver/unix/NetStat.java
oshi-core/src/main/java/oshi/jna/platform/mac/SystemB.java
oshi-core/src/main/java/oshi/jna/platform/windows/IPHlpAPI.java
oshi-core/src/main/java/oshi/software/common/AbstractInternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/InternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxInternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/mac/MacInternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixInternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdInternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisInternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsInternetProtocolStats.java
oshi-core/src/main/java/oshi/util/FileUtil.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/platform/linux/ProcPath.java
oshi-core/src/test/java/oshi/software/os/InternetProtocolStatsTest.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java
oshi-demo/pom.xml
oshi-dist/pom.xml
pom.xml

Fixes #1422.  I've implemented native code for Windows, macOS, and Linux.  
The linux code relies on `/proc/net` which is allegedly deprecated but is the easiest route. There's a much more complicated way of doing it using tcp_diag, noted on #1422, which someone else can put in if they want it.
I've got a default implementation using `netstat` for the unix ports.  They each have more direct native options (FreeBSD via a systctl call) but are complex enough that I'm not interested in doing them now.

TCP and UDP connection listing

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacHWDiskStore.java

Looking up a disk from a filesystem does not lead to the physical,
but to a "synthesized" disk, which cannot be traversed to an entry
with a IOBlockStorageDriver parent.
However, the APFSConainerScheme contains the statistics as well,
(except for the timers, which this change omits)
```
$ df -h /
Filesystem     Size   Used  Avail Capacity iused      ifree %iused  Mounted on
/dev/disk1s5  466Gi   10Gi   68Gi    14%  488564 4882988356    0%   /
$ diskutil list
/dev/disk0 (internal, physical):
#:                       TYPE NAME                    SIZE       IDENTIFIER
0:      GUID_partition_scheme                        *500.3 GB   disk0
1:                        EFI EFI                     209.7 MB   disk0s1
2:                 Apple_APFS Container disk1         500.1 GB   disk0s2
/dev/disk1 …
```

Also get disk statistics from AppleAPFSContainerScheme

---

oshi-core/src/main/java/oshi/software/os/InternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxInternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/mac/MacInternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsInternetProtocolStats.java

Linux uses `FIN_WAIT1` and `FIN_WAIT2` but has its own implementation. Unix implementations use `FIN_WAIT_1` and `FIN_WAIT_2` and the code relies on this spelling

Switch to Unix standard netstat state

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworkIF.java

Windows bit fields are in little-endian order.

Fix NetworkIF.isConnectorPresent() on Windows

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworkIF.java
oshi-core/src/main/java/oshi/jna/platform/mac/SystemConfiguration.java
oshi-core/src/test/java/oshi/hardware/NetworksTest.java

`NetworkIF.getIfAlias()` for Windows and Linux.  Relates to #1541

Expose the alias of a network interface

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworkIF.java
oshi-core/src/test/java/oshi/hardware/NetworksTest.java

ifAlias was not initialized properly on Windows before Vista.

Fix a NPE in NetworkIF.toString() on Windows.

---

oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworkIF.java
oshi-core/src/test/java/oshi/hardware/NetworksTest.java

Expose the `ifOperStatus` as described in [RFC 2863](https://tools.ietf.org/html/rfc2863) as `NetworkIF.getIfOperStatus()`.

Expose network interface operational status

---

oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java
oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java

Including the parent pid in the process list prevents an inefficient call to create it just for the process start time. Fixed other bugs and inefficiencies.

Remove redundant process list calls for descendants

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/test/java/oshi/hardware/CentralProcessorTest.java

Fixes #1583 (or at least doesn't return incorrect values)

macOS doesn't provide system level context switches or interrupts

---

pom.xml

This used to work, but I've had to manually type my passphrase since upgrading to 2.1. And I always fat-finger it.

(Re-)allow maven-gpg-plugin to use gpg.passphrase in settings.xml

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterQuery.java

Profiling identifies the largest significant non-native CPU time is associated with the localization of PDH counter strings.  The localization code is inefficient, an O(n<sup>2</sup>) process where every counter string is individually localized by querying the entire list of strings to fetch an index, which is then passed to native code to query the localized value.
These localized strings don't change so it makes sense to cache them.  It's still slightly inefficient for the first insertion but will be non-blocking O(1) lookup once the string has been initially localized.

Cache localized perf counter object strings

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java

Remove redundant check for isLocalInterface. JDK already [does that](https://github.com/openjdk/jdk/blob/3423f3e1f5a2120e8f761a238c2929c44957760d/src/java.base/share/classes/java/net/NetworkInterface.java#L526) so it improves performance.
This PR solves https://github.com/oshi/oshi/issues/1606

Improve performance AbstractNetworkIF::isLocalInterface

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java

While testing FreeBSD support in a separate PR, I noticed that some processes weren't getting listed. Debugging it further, I found that `ps(1)` was printing the following:
```bash
$ uname -a
FreeBSD freebsd 13.0-RELEASE FreeBSD 13.0-RELEASE #0 releng/13.0-n244733-ea31abc261f: Fri Apr  9 04:24:09 UTC 2021     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
$ ps -awwxo state,pid,ppid,user,uid,group,gid,nlwp,pri,vsz,rss,etimes,systime,time,comm,majflt,minflt,nvscw,nivscw,args
ps: nvscw: keyword not found
ps: nivscw: keyword not found
STAT  PID PPID USER        UID GROUP       GID NLWP PRI     VSZ   RSS ELAPSED   SYSTIME      TIME COMMAND            MAJFLT MINFLT COMMAND
DLs     0    0 root          0 wheel         0  368 -16       0  5888    2667   0:10.32 …
```

FreeBSD process listing results in "keyword not found" errors

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxUsbDevice.java

This change fixes a leaking device reference in the Linux USB device implementation. When an interface device is encountered (i.e. devtype is "usb_device") the rest of the loop was skipped and the allocated device would never be unreferenced. This change adds an additional explicit unreference in this case.
This was the underlying leak causing the issue reported by @botto in #1670

Fix leaking udev reference in LinuxUsbDevice

---

oshi-core/src/main/java/oshi/SystemInfo.java

currentPlatform variable initialized in static block of this class.
But it's also accessed via constructor for validate unsupported environment.
This variable possible not initialized yet when access make a instance use constructor.
I'm already met this kind of issue when I run unit test use this library.
I think one more variable init checking required, at least If constructor want to check unsupported or not.

Initialization timing issue for static variable

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOSThread.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSThread.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOSThread.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOSThread.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

I really like this improvement for ps argument lists.  Much less error prone.  FreeBSD processes done, will do for other *nix PS lists for processes and threads.
@basil what do you think?

Replace ps argument lists with enum

---

oshi-core/src/main/java/oshi/SystemInfo.java

#1671 not worked for me.
Run CI with snapshot version but I saw same error message below.
```
[ERROR] display as string  Time elapsed: 0.016 s  <<< ERROR!
java.lang.UnsupportedOperationException: Operating system not supported: JNA Platform type 2
Caused by: java.lang.UnsupportedOperationException: Operating system not supported: JNA Platform type 2
```
JNA could recognize current os in static block when failed on a constructor of SystemInfo class.
So I tried check unknown environment by JNA method instead of OSHI. At the result my CI passed successfully.
I'm not sure what is exact reason. But I just think that JNA and OSHI depends on many static initialization and it's make not easy to assume proper working.
In my opinion, static blocks and variables should be minimized.
But if OSHI have …

Move supported operating system check out of SystemInfo constructor

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/unix/aix/PsInfo.java
oshi-core/src/main/java/oshi/driver/unix/solaris/PsInfo.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/jna/platform/unix/CLibrary.java
oshi-core/src/main/java/oshi/jna/platform/unix/freebsd/FreeBsdLibc.java
oshi-core/src/main/java/oshi/jna/platform/unix/openbsd/OpenBsdLibc.java
oshi-core/src/main/java/oshi/jna/platform/unix/solaris/SolarisLibc.java
oshi-core/src/main/java/oshi/jna/platform/windows/NtDll.java
oshi-core/src/main/java/oshi/jna/platform/windows/Shell32.java
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOSProcess.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/java/oshi/util/FileUtil.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/platform/linux/ProcPath.java
oshi-core/src/main/java/oshi/util/platform/mac/SysctlUtil.java
oshi-core/src/main/java/oshi/util/platform/unix/freebsd/BsdSysctlUtil.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java
pom.xml

Fixes #369. Posting this draft for initial feedback on the API and the overall strategy. The Linux implementation is shamelessly copied from the (MIT-licensed) code in Jenkins core. If this approach of moving code from Jenkins core into this project is deemed suitable, I'll look into moving over the Jenkins implementations for macOS, AIX, and Solaris and writing new implementations for the BSDs.

API for process arguments and environment

---

pom.xml

Reverts oshi/oshi#1672
Getting this error trying to release:
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.9.1:site (default-site) on project oshi-parent: Execution default-site of goal org.apache.maven.plugins:maven-site-plugin:3.9.1:site failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-site-plugin:3.9.1:site: java.lang.AbstractMethodError: Receiver class org.apache.maven.doxia.module.markdown.MarkdownParser does not define or inherit an implementation of the resolved method 'abstract void parse(java.io.Reader, org.apache.maven.doxia.sink.Sink)' of interface org.apache.maven.doxia.parser.Parser.
>     [ERROR] -----------------------------------------------------
>     [ERROR] realm = …

Revert "Bump doxia-module-markdown from 1.9.1 to 1.10"

---

CHANGELOG.md
UPGRADING.md
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java

Removed deprecated process sorting methods from the OperatingSystem class. Task 5 in issue #1723.

removed deprecated process sorting methods from OperatingSystem class.

---

CHANGELOG.md
UPGRADING.md
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java

This is a fix to the third issue mentioned in https://github.com/oshi/oshi/issues/1723. The OSProcess javadoc and UPGRADING.md have been fixed as required.

Changed the return value of getCommandLine() method of linuxOSProcess and macOSProcess from null-delimited string to space-delimited string

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java
oshi-core/src/test/java/oshi/hardware/NetworksTest.java

Changed return type of the NetworkInterface method getMTU() from int to long in all its OS implementations.

Changed return type of getMTU() from int to long

---

.github/workflows/macos.yaml
.github/workflows/windows.yaml

- "adopt" is now deprecated, use "temurin"
- java 17 was released
- jav 16 is EOL
- java 18 is now early access
- add Windows 2022 (beta)

[CI] Update Java versions for Windows and MacOS workflows

---

oshi-core/src/main/java/oshi/util/platform/unix/solaris/KstatUtil.java
oshi-core/src/test/java/oshi/hardware/DisksTest.java

A disk on a VM that failed the first stats read with 0's shouldn't fail an update of the same 0's.
Also reducing the log level for failed kstats.

Tweak tests and logs for persnickety Solaris VM

---

oshi-core/src/main/java/oshi/util/ParseUtil.java

I don't know how to link this pull request to issue #1788

Don't attempt to parse optional regex match if it is null, fixes #1788

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/ExecutingCommand.java

adding close streams clause in getProcessOutputAndDestroy prior to destroy
in Solaris, p.destory failed to close the streams, so we need to close the streams explictly

Fix fd leaks in Solaris after Runtime.exec calls

---

CHANGELOG.md
oshi-core/pom.xml
oshi-core/src/test/java/oshi/driver/linux/DevicetreeTest.java
oshi-core/src/test/java/oshi/driver/linux/DmidecodeTest.java
oshi-core/src/test/java/oshi/driver/linux/LshalTest.java
oshi-core/src/test/java/oshi/driver/linux/LshwTest.java
oshi-core/src/test/java/oshi/driver/linux/SysfsTest.java
oshi-core/src/test/java/oshi/driver/linux/WhoTest.java
oshi-core/src/test/java/oshi/driver/linux/proc/CpuInfoTest.java
oshi-core/src/test/java/oshi/driver/linux/proc/CpuStatTest.java
oshi-core/src/test/java/oshi/driver/mac/WhoTest.java
pom.xml

update al leftover testcases to use `org.junit.jupiter.api.Test`, either this was leftover from #1387 or these imports snuck back in when adding/updating these test cases
see: https://github.com/oshi/oshi/issues/1794#issuecomment-978938037

Ban the use of `junit:junit` (4.x) and `org.hamcrest:hamcrest-core` (1.3)

---

pom.xml

Redo of #1802.
WIth the new version I don't have to specify static separately, so the configuration is pretty streamlined.  I like that the checkstyle plugin can be very strict on the modular part, allowing this to be a little more lenient.  But using enforcer has the advantage of working with mvn test (or most other maven commands), and not requiring a separate "checkstyle:check" call.  
Set as draft because it's using a snapshot dependency, but wanted to stick this up here for @mprins  and @hazendaz  review.  Will wait to merge until it's a released version.

Restrict imports with maven enforcer

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/ExecutingCommand.java

Closing streams before ProcessBuilde.destroy() for Windows, since Windows JDK implementation just calls the native TerminateProcess which is equivalent to kill

Windows: Closing streams before ProcessBuilde.destroy()

---

oshi-core/src/main/java/oshi/jna/platform/mac/IOKit.java
oshi-core/src/main/java/oshi/util/platform/mac/SmcUtil.java

JNA `Structure` requires reflective access to subclasses. Moving these structures simplifies `exports ... to` statements in the module descriptor.

Refactor SMC structures into JNA class for module consistency

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/resources/oshi.properties

Enumeration of sysfs via udev saves a command line call for numa node info, and will enable easier hybrid topology detection in #1571.

Use udev for Linux cpu enumeration and frequency

---

.github/workflows/aix.yaml
.github/workflows/freebsd.yaml
.github/workflows/linux.yaml
.github/workflows/macos.yaml
.github/workflows/openbsd.yaml
.github/workflows/pr.yaml
.github/workflows/solaris.yaml
.github/workflows/sonar.yaml
.github/workflows/sonatype.yaml
.github/workflows/windows.yaml

The `license-maven-plugin` version 4.2 enabled a new feature to use the file's creation date and last edit date as a copyright range, which we have now configured.  However, this new feature:
- is resource intensive, navigating the git history for each file
- breaks on shallow clones, since git history doesn't identify the oldest commit per file properly
Our CI workflows using the `actions/checkout` GitHub Action are shallow clones (to improve performance), using a default `fetch-depth` of 1.  This results in all license headers being incorrectly rewritten (and then thrown away) during CI runs.
Even without rewriting, the multiple checks are unneded.  This PR skips the `license:format` goal for CI, and only executes `license:check` once on PRs (after fetching full history).

Skip license header rewrites on CI

---

.github/workflows/pr.yaml
.github/workflows/windows.yaml
CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/openbsd/OpenBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/test/java/oshi/hardware/CentralProcessorTest.java

Adds a `getPhysicalProcessors()` method to `CentralProcessor` which returns a list.  Each `PhysicalProcessor` includes:
- a core id
- an efficiency measure to identify relative performance vs. efficiency tradeoffs
- a string with processor identification information

Add support for modular/hybrid processor topology

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java

A 4-package 8-core machine has only core_id 0 and 1 in each of the packages

Add package ID to PhysicalProcessor object for uniqueness

---

oshi-core-shaded/pom.xml
oshi-core/pom.xml
oshi-demo/pom.xml
oshi-dist/pom.xml
pom.xml

Fixes #1145 
When a module creating a shaded JAR using `maven-shade-plugin` has a manifest in `maven-jar-plugin` that includes an Automatic Module Name, the `maven-javadoc-plugin` fails (since 3.2.0).
Fixed by using inheritance with appending for the manifest, and only including the Automatic Module Name in the `oshi-core` artifact.

Use automatic name only for oshi-core

---

.github/workflows/linux.yaml
.github/workflows/macos.yaml
.github/workflows/pr.yaml
.github/workflows/sonatype.yaml
RELEASING.md
config/module-info.java
config/module-info.test
mvnw11
oshi-core/pom.xml
pom.xml

See #1862 for some background.
These changes greatly simplify the maintenance and release of the modular artifacts by eliminating the need to maintain a separate branch.  A new branch is only needed for releasing (due to version change commits).
- Uses a `java11` profile to customize the pom:
- Controls which maven modules are used
- Updates properties for compiler source and target levels
- Ignores the incompatible animal-sniffer plugin
- Adds a `mvnw11` script that wraps the maven wrapper
- Copies module descriptor and modular test files for the modular build and cleans them up afterwards
- Updates artifactID in required pom files since that can't be done in a profile and reverts afterward
- Updates dependencies in the pom that will be uploaded with the deployment so downstream projects …

Streamline modular artifact release process

---

pom.xml

This plugin emits a warning if not setup properly.  This is the default setup.  While they just released a new cut they haven't done anything that might assist at making this default unfortunately so adding it so the warning goes away on site generation.

[pom] Define general taglist setup to get rid of warning (legacy warning meant not setup)

---

pom.xml

Reverts oshi/oshi#1890
2.x is needed as a workaround for coveralls to work on JDK 11+.

Revert "Bump jakarta.xml.bind-api from 2.3.3 to 3.0.1"

---

pom.xml

If I recall, I had gotten this documented and noted on license plugin sometime ago.

[pom] Skip license plugin during release cycle as code is shallowed cloned

---

.github/workflows/macos.yaml
.github/workflows/pr.yaml
.github/workflows/site.yaml
pom.xml

Removed all automatic license checking in the POM and added an explicit license:check call in the PR workflow.  Eclipse wasn't happy with its earlier lifecycle placement and in reality it just doesn't need to be run that often.  PRs should catch most issues, and I've got my own local macro that does license:check, sortpom:sort, and spotless:apply regularly.
Also switched site workflow to run on jdk8.  The site build was failing on the java11 javadocs -- seems the config I put in needed to be in `<build>` for the release but in `<reporting>` for site.  Rather than duplicate the config, it's easy just to not generate the redundant or unnecessary content for the modules built in the JDK11+ profile by running the workflow on JDK 8.

Remove automatic license checks except PR workflow

---

pom.xml

Reverts oshi/oshi#1929
A change to the maven-compiler-plugin adds missing package-info files, but it seems to not work on Windows in conjunction with mvn-bnd-plugin.  Reverting until the next version.

Revert "Bump maven-compiler-plugin from 3.9.0 to 3.10.0"

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/resources/oshi.properties
src/site/markdown/FAQ.md

Moves the initial tick storage into the WindowsCentralProcessor object so it can be effectively reset with a new SystemInfo object.
Detects base counter rollover via negative delta (will catch most problems with reasonably frequent polling) or non-sane tick ratio.  Documents suggestion to handle other edge cases.

Handle Processor Utility 32-bit counter rollover

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/platform/unix/solaris/KstatUtil.java

Still trying to address #1934.  
Kstat chain was being opened outside of locking by power supply class. This may have caused threading issues.

Don't open kstat chain outside of locking

---

oshi-core/src/main/java/oshi/jna/platform/unix/Kstat2.java

Reverts oshi/oshi#1964
Seems it was correct the old way.

Revert "Fix Kstat2 array mappings"

---

.travis.yml

Travis gives the ability to encrypt the token for Sonar, making it available for PR workflows.  If I can get this working we can remove Scrutinizer.

Add Sonar to travis configuration

---

pom.xml
src/site/site.xml

Note: Added maven scm publish plugin as it appears maven is going towards that being way to publish.  It does not help the slow checkout issue but deploy is skipped right now outside 'site' branch so this does no harm either.  Will come back to this as they refine process at a future date.
I am not sure if this config will affect the site.yaml file.  We would need to confirm that.  It also is forcing some of underlying items on site plugin so scm used is consistent.  
wagon-ssh is deprecated and removed in version 2 as I have here for scm.  This works through unwrapping (ie scm contains git which contains ssh).  Ultimately this makes it match the other distribution setup.  The site will work this way on release if wanted but long time to process.  Using scm plublish is separate if you …

[site] Rework site so it works from local

---

pom.xml

fails if using default staging, use this to ensure it picks up site as it varies with release.
During release, tested now, this failed without this setting.  Added this in the release portion so running site site:deploy scm-publish:publish-scm will still work without issue.  What I don't know is if any of the site is missed.  Testing thus far is on release of project(s) that are themselves one pom relying on a super pom stored elsewhere.  I'm not sure how multi module works during release.  So @dbwiddis you will want to watch out on next release to see if this along with what was merged arleady does in fact update all portions of the site.  Like you, I don't have something really specific to release yet so I'm not sure if you or I will make it this far first on multi module.

[pom] Add adjustment to 'content' for release profile with scm plugin

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Fixes #2032 
Initial commit creates a boolean constant to determine whether to use Udev or a fallback.
~Draft PR, need to get a compatible implementation without udev.~

Graceful fallback for CPU Topology without udev

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxHWDiskStore.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxLogicalVolumeGroup.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxPowerSource.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxUsbDevice.java

Follow up to #2033 to test for udev presence rather than throwing exception.  Added graceful fallback for network info and log warnings for other implementations.

Fallback or log warning to avoid exception with no udev

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterQuery.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java

Fix in #1662 was overzealous; we need localized instances for wildcard queries but English object names.

PDH wildcard counters need localized instances

---

CHANGELOG.md
oshi-core-java11/pom.xml
oshi-core/src/main/java/oshi/SystemInfo.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
src/site/markdown/FAQ.md
src/site/markdown/index.md

As Android is based on Linux, reusing LinuxOperatingSystem and LinuxHardwareAbstractionLayer works for the most important parts (CPU, RAM, system description etc.).
Tested on Android 7, 9 and 11.
Resolves https://github.com/oshi/oshi/issues/1533.

Added support for Android OS

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java
oshi-core/src/main/java/oshi/software/os/OSThread.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOSProcess.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Not sure if this was done, 
Adds parallel on every stream call 
Fixes #2196 
@dbwiddis I'm not actually sure when parallel should be used according to
https://www.baeldung.com/java-when-to-use-parallel-stream
so I have never actually used this method, is it necessary to use `.parallel` on every stream call?

Improve performance using parallel streams for processes and threads

---

oshi-demo/pom.xml

Wouldn't normally bump to a RC but this is getting flagged for security.   We aren't vulnerable as we haven't opted in to the setting, but I figure why not update to make the warning go away? 
Curious if there's a way to tell Renovate to do this update without changing configs...
https://security.snyk.io/vuln/SNYK-JAVA-COMFASTERXMLJACKSONCORE-3038426

Bump jackson-databind to 2.14.0-rc1

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Detect Windows Server 2022 in older JDKs

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java

Use regex to pre-filter to parseable CPU numbers for ARM Macs

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java

This should finally fix the AIX tests!

Don't assume ticks match logical processor count

---

pom.xml

Extends the SLF4J version range for OSGi environments, so SLF4J 1.7 for instance doesn't raise a conflicts with latest oshi-core.
Fixes https://github.com/oshi/oshi/issues/2326

Allow using SLF4J 1 in OSGi containers

---

oshi-core-java11/pom.xml

No longer needed!  `mvn test test` doesn't fail any more.

Remove auto-clean workaround for testing plugin bug

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java
oshi-demo/src/main/java/oshi/demo/gui/ProcessPanel.java

Clock ticks on Apple Sillicon are 24 million per nanosecond, which impacts the per-process ticks.  Also fixed a math bug in the demo GUI.
Fixes #2346

Convert per-process CPU ticks on Apple Silicon to ms

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/util/GlobalConfig.java
oshi-core/src/main/resources/oshi.properties

Allows users to force use of the deprecated kstat API even if kstat2 is available
Fixes #2348 (or at least allows users to work around it)

Make use of Kstat2 configurable

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsNetworkParams.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

1. WindowsNetworkParams didn't fall back to superClass on failure like all the other OS's.
2. May as well assert not null to get a CIMDateTime parsing test failure rather than relying on the NPE to fail the test.

Address some Coverity Scan issues

---

.github/workflows/openbsd.yaml

The default jdk for maven is 8, but some maven plugins no longer work, the jdk version is specific for the OBSD release, ic. 7.3 ; there is no meta package like eg. "jdk-11"
see. https://github.com/oshi/oshi/issues/2373#issuecomment-1556191016

Update openbsd.yaml to install jdk11

---

.github/workflows/openbsd.yaml

The special `package%branch` syntax appears to work to get the correct JDK 11.
`pkg_add jdk%11` installs `jdk-11.0.16.8.1v0`

Use branch matching for OpenBSD JDK 11 lookup

---

CHANGELOG.md
oshi-core/src/main/java/oshi/jna/platform/linux/LinuxLibc.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/util/platform/linux/ProcPath.java

#2389 
gettid
Glibc does not provide a wrapper for this system call; call it using syscall(2).
#define _GNU_SOURCE
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/types.h>
int
main(int argc, char *argv[])
{
pid_t tid;
tid = syscall(SYS_gettid);
}

fix undefined symbol: gettid #2389

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java
oshi-core/src/main/java/oshi/util/UserGroupInfo.java

Improves performance of Linux user queries by:
- only querying the passwd/group when asked
- increasing map caching time to 5 minutes
- always trying /etc/passwd or /etc/group first
- only using getent with an id when the etc file lookups fail

Improve performance of Linux User and Group name queries

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java

issue:
The result of OSProcess#getThreadDetails() in WindowsOSProcess implementation is allways empty array. #2432

Fix the result of OSProcess#getThreadDetails() in WindowsOSProcess implementation is allways empty array.

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

On some platforms, the case of cpuinfo entry names does not match the names hardcoded in oshi.
For example, `/proc/cpuinfo` on linux loongarch64 looks like this:
```
system type             : generic-loongson-machine
processor               : 0
package                 : 0
core                    : 1
global_id               : 0
CPU Family              : Loongson-64bit
Model Name              : Loongson-3A6000
CPU Revision            : 0x00
FPU Revision            : 0x00
CPU MHz                 : 2500.00
BogoMIPS                : 5000.00
TLB Entries             : 2112
Address Sizes           : 48 bits physical, 48 bits virtual
ISA                     : loongarch32 loongarch64
Features                : cpucfg lam ual fpu lsx lasx crc32 complex crypto lvz lbt_x86 lbt_arm lbt_mips
Hardware …
```

Fix parsing Loongson CPU names

---

.github/workflows/aix.yaml
CHANGELOG.md
oshi-core/src/test/java/oshi/driver/unix/aix/perfstat/PerfstatTest.java

The AIX machine we use for testing includes two virtual optical drives with 0 size and other stats.
While there are multiple signals this isn't a "real" drive, the `time` stat (amount of time disk is active) seemed the least likely to exclude real disks.
Fixes #2437 
Fixes #2459

Fix AIX tests for virtual/unused drives

---

.github/workflows/linux.yaml
.github/workflows/pr.yaml
oshi-core/src/test/java/oshi/util/FormatUtilTest.java
oshi-core/src/test/java/oshi/util/GlobalConfigTest.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

The check runs during the verify phase, which was failing snapshot deployment.  Added the check to CI for test as well as main to catch it earlier.

Fix ForbiddenAPIs for test classes

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/PerfmonConstants.java
oshi-core/src/main/java/oshi/driver/windows/perfmon/PerfmonDisabled.java
oshi-core/src/main/java/oshi/driver/windows/perfmon/ThreadInformation.java
oshi-core/src/main/java/oshi/driver/windows/registry/ProcessPerformanceData.java
oshi-core/src/main/java/oshi/driver/windows/registry/ThreadPerformanceData.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSThread.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java
oshi-core/src/main/resources/oshi.properties
oshi-core/src/test/java/oshi/SystemInfoTest.java

Bypasses registry query for thread details (which can't be filtered) and directly queries performance monitors only for the requested process when getting process thread details.  
```
[INFO] Trying the old way:
[INFO]   Total time: 805ms
[INFO] Trying the new way:
[INFO]   Total time: 47ms
```
Fixes #2483

Improve performance of thread details query for a single process

---

.github/workflows/macos.yaml
.github/workflows/pr.yaml
.github/workflows/windows.yaml

Codecov can handle multiple coverage report uploads and merges the results.
Adding reporting for Windows and macOS to existing reports ~and removing the path excludes~.

Add coverage reports for Windows and macOS to existing Linux

---

.mvn/maven.config

Noticed when looking into config for nvd that this was not present.  This does two things automatically.  The first option will ensure that when released to central, it will show sha-256 and sha-512.  Most major projects are now doing this.  The second option forces its hand to download more secure checksums.

[mvn] Add more secure checksums

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGraphicsCard.java

fix #2521: 
Changed GPU info gathering mecahism for Windows.
Using Win Registy values, instead of Win32 api calls, so now vram more than 4GiB can be detected properly

 fix #2521: Wrong VRam value 

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Catch all `NoClassDefFoundError` to give better logs on missing JNA classes when initializing LinuxOperatingSystem.

Improve handling of missing JNA classes in LinuxOperatingSystem init

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/util/GlobalConfig.java
oshi-core/src/main/resources/oshi.properties

As discussed in https://github.com/oshi/oshi/discussions/2561#discussioncomment-8090621 adds a configuration option `oshi.os.linux.allowudev` (default: `true`) to actively disable use of udev to load more detailed device information.
- If we'd prefer to invert the property to be `_disabled` instead, I can do that too.
- Solaris `allowKstat2` uses a type of camel case format. I can follow that, but other properties don't use that (`logwarning`, `commandline` etc) so bit unsure which format to follow.
- I didn't add a specific test as it'd need a VM fork for the test due to the use of `static` (or some bytecode/classloader magic)
Validated that this does work for the specific use case in the discussion:
**After**
```
jvm 1    | 2024-01-11 12:50:14,683 INFO  [main] AgentStatusHttpd:66 - …
```

Allow opting out of udev usage via GlobalConfig

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/proc/CpuInfo.java
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/openbsd/OpenBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/jna/platform/windows/Kernel32.java
oshi-core/src/main/java/oshi/util/platform/mac/SysctlUtil.java
oshi-core/src/test/java/oshi/SystemInfoTest.java

Adds feature flags to Central Processor
Can't find anything helpful for AIX
Fixes #2589

Add getFeatureFlags method to CentralProcessor interface

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/proc/CpuStat.java
oshi-core/src/main/java/oshi/util/FileUtil.java

Add a new method, FileUtil.readLines, which accepts a number of lines to read and allocates an ArrayList which contains a number of elements corresponding to the number of lines to be read. If file is not readable, return Collections.emptyList() to avoid allocating a list.
Use this new method in CpuStat.getSystemCpuLoadTicks to avoid allocating a String for each line in /proc/stat, instead allocating a single String and ArrayList with a capacity of one.
This reduces allocation of char[]'s to back the String for each line by two orders of magnitude (from a few kB to a few tens of bytes) on each call.

Reduce CpuStat.getSystemCpuLoadTicks memory allocation pressure

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/proc/ProcessStat.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxInternetProtocolStats.java

fix the issue(#2639 ) where the owning process ID sometimes returns -1 caused by it.

fix #2639: getOwningProcessId sometimes return -1 on 64x linux

---

CHANGELOG.md
oshi-core/src/main/resources/oshi.macos.versions.properties

Add macOS 15 (Sequoia) to version properties

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java
oshi-core/src/main/java/oshi/util/FileUtil.java

When the process is gone, there shouldn't be any error logging in the command line.
Fixes https://github.com/oshi/oshi/issues/2689

Do not log errors for reading process arguments on Linux

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java

Uses the method parameter for the map lookup instead of the (uninitialized) vendor.  
Fixes #2703 (and properly fixes the original #2513 bug)

Properly parse CPU vendor when lscpu not available

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/util/GlobalConfig.java
oshi-core/src/main/resources/oshi.properties

Restores the System CPU code removed in #1400 under an optional configuration.
This method may give inaccurate results when there is more than one processor group (more than 64 processors) but may be necessary for service accounts to read values without special permissions.

Restore optional legacy method of calculating Windows System CPU

---

.github/workflows/macos.yaml
.github/workflows/pr.yaml

This PR replaces the use of FlyCI macOS runners with GitHub ones since FlyCI macOS runners will be discontinued effective Sep 30, 2024. 
[Read more about the discontinuation of the FlyCI macOS runners](https://flyci.net/blog/flyci-discontinue-macos-runners?utm_source=site_link&utm_medium=github&utm_campaign=discontinue-runners).

Replace FlyCI macOS runners with GitHub macOS runners

---

oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java

when the systctl call fails.
Fixes #2710

Do not log error on macOS for hw.nperflevels

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java

The output result of  `/sys/class/net/<card>/speed` is in Mbps and needs to be converted to bps

Fix speed value for LinuxNetworkIF

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/GlobalConfig.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterQuery.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java
oshi-core/src/main/resources/oshi.properties

Reduces redundant WARN logs on performance counter failures:
- Initial failure error code message reduced to DEBUG
- Disabling counters message reduced to INFO
- Added config property to disable all counters and use WMI on a failure of any one
Fixes #2721

Reduce redundant logging on perf counter failures

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/platform/linux/SysPath.java

Fix the issue of not being able to obtain the CPU temperature due to the THERMAL value error in the Linux environment.

Fix Linux CPU thermal zone path string

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java
oshi-core/src/main/resources/oshi.properties

This PR will add a priority to the thermal zones, in the past the last termal zone found was reported as CPU temp.
In my local system this resolves to the sensor on the M2 disk, this might be the reason for #2791 too.
The priority is defined in a local list and unmapped types are treated as lowest priority.
In case there are multiple sensor with the same priority the last one does win, like in the past.

Enable configurable prioritization of thermal zones

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

The `/proc/device-tree/model` file usually ends with NUL, but oshi does not trim it.
For example, for the Raspberry Pi 4B, the content of this file is `"Raspberry Pi 4 Model B Rev 1.4\0"`. 
This causes `new oshi.SystemInfo().getHardware().getProcessor().getProcessorIdentifier().getName()` to return a NUL-terminated string if oshi cannot obtain the processor name from `/proc/cpuinfo`.
We should trim the string to avoid this.

Trim the trailing NUL of /proc/device-tree/model

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/EdidUtil.java
oshi-core/src/test/java/oshi/util/EdidUtilTest.java

It used to miss a few bits on the second and third, see issue #2803. 
This pull request changes the substring in the method to include the right bits.

Fixes manufacturer ID parsing logic in getManufacturerID()

---

oshi-core/src/main/java/oshi/hardware/Sensors.java

Add a link to jLibreHardwareMonitor so users know how to include this dependency and remove the duplicate description of getCpuTemperature about OHM.

Modify API description of Sensors

---

pom.xml

https://github.com/oshi/oshi/issues/2834

Configure bnd-maven-plugin to make librehardwaremonitor optional

---

.github/workflows/windows.yaml

Add Windows 2025 / Java 21 combination to build matrix. Windows 2025 is in "Public Preview" so marking as experimental

Windows 2025

---

.github/workflows/pr.yaml
.github/workflows/windows.yaml
CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32BaseBoard.java
oshi-core/src/main/java/oshi/hardware/Sensors.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsBaseboard.java

Adds the PRODUCT field on Win32_Baseboard as a backup for (or amplification of) the MODEL field.
Fixes #2831

Improve Windows baseboard model identification

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Users who keep their JDKs up to date (like GitHub runners) already have proper parsing, but for earlier patch versions of the JDK, this accomplishes the same logic.

Resolve Windows Server 2025 on older JDKs

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxInternetProtocolStats.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/platform/linux/ProcPath.java

Optimize calls to netstat by using /proc files (Issue #2826)
This PR optimizes the retrieval of network statistics by replacing external netstat calls with direct file reads from /proc/net/snmp (TCPv4 and UDPv4) and /proc/net/snmp6 (UDPv6).
- Replaced netstat calls with parsing /proc/net/snmp (TCPv4 and UDPv4) and /proc/net/snmp6 (UDPv6)
- Updated LinuxInternetProtocolStats.java to extract TCP and UDP statistics 
- Verified that the extracted TCP/UDP statistics match the output from cat /proc/net/snmp and cat /proc/net/snmp6
- Confirmed correctness by comparing values before and after changes
- Tested on various flavors of Linux such as Redhat, Amazon Linux 2, etc by creating a simple Java App and printing the TCP and UDP stats

Optimize netstat calls using /proc files (Issue #2826)

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxGraphicsCard.java

This PR extends the Linux GPU detection logic to recognize 3D controller devices (class [0302]) in addition to the existing VGA class check. Many discrete NVIDIA GPUs (such as the RTX A2000) are now reported as "3D controller" instead of "VGA", causing OSHI to miss them when multiple GPUs are present, for instance, in systems with both an integrated GPU and a discrete GPU. In cases where only a single GPU is present, the current code falls back to using `lshw` to retrieve GPU info, which usually works as expected. However, because the lspci-based detection is used first, the discrete dGPU isn’t detected unless we also check for the 3d controller class. For example, consider this `lspci` output for two cards:
```
Class: VGA compatible controller [0300] 
Vendor: Intel Corporation [8086] …
```

Include 3D controller ([0302]) in Linux GPU detection

---

CHANGELOG.md
config/checkstyle-suppressions.xml
oshi-core/src/main/java/oshi/software/os/unix/aix/AixInstalledApps.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOperatingSystem.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

**Context**:
The standard `lslpp -Lc` command lists installed software in AIX.
**Code Changes**:
- Use `lslpp -Lc` to extract installed application data.
- Parse the following fields from each colon-separated line:
- name → field index 0
- version → index 2
- description → index 7
- installPath → index 16
- timestamp → index 17 (can be either yyww or full datetime)
- Skip the first line (column headers).
- https://www.ibm.com/docs/en/aix/7.1.0?topic=l-lslpp-command
Column names -> https://community.unix.com/t/list-of-installed-applications/338886
The command lists installed software in AIX, but lacks explicit vendor information
In the PR `AixInstalledApps` class consists of the sample outputs from the command in comments
**Replication:**
Used AIX 7.1 ppc64.
Created a simple Java program …

Installed apps feature for AIX

---

oshi-core-java25/src/main/java/oshi/ffm/mac/CoreFoundationFunctions.java
oshi-core-java25/src/main/java/oshi/ffm/mac/CoreFoundationHeaders.java
oshi-core-java25/src/main/java/oshi/ffm/mac/ForeignFunctions.java
oshi-core-java25/src/main/java/oshi/ffm/mac/IOKit.java
oshi-core-java25/src/main/java/oshi/ffm/mac/IOKitFunctions.java
oshi-core-java25/src/main/java/oshi/ffm/mac/IOKitHeaders.java
oshi-core-java25/src/main/java/oshi/ffm/mac/IOKitUtil.java
oshi-core-java25/src/main/java/oshi/ffm/mac/MacSystemFunctions.java
oshi-core-java25/src/main/java/oshi/software/os/mac/MacOSProcessFFM.java

Did my best to port JNA's IOKit classes to FFM, with the util class behaving identically.  
Implemented in one place (so far), now completely on FFM for MacOperatingSystem and MacOSProcess classes.

Implement IOKit with no-code-change Util class

---

CHANGELOG.md
oshi-core/src/main/resources/oshi.macos.versions.properties

Adds macOS Tahoe's version mapping to `oshi.macos.versions.properties`.

Add macOS 26 (Tahoe) codename mapping

---

CHANGELOG.md
oshi-core-java25/src/main/java/oshi/ffm/windows/Advapi32FFM.java
oshi-core-java25/src/main/java/oshi/ffm/windows/Kernel32FFM.java
oshi-core-java25/src/main/java/oshi/ffm/windows/PsapiFFM.java
oshi-core-java25/src/main/java/oshi/ffm/windows/WinNTFFM.java
oshi-core-java25/src/main/java/oshi/software/os/windows/WindowsOperatingSystemFFM.java
oshi-core-java25/src/main/java/oshi/util/platform/windows/Advapi32UtilFFM.java
oshi-core-java25/src/main/java/oshi/util/platform/windows/Kernel32UtilFFM.java

_isElevated()_ – Checks whether the current process is running with elevated (administrator) privileges.
_getSystemBootTime()_ – Retrieves the system boot time via native Windows APIs.
_getThreadCount()_ – Returns the total number of threads in the system using GetPerformanceInfo.
_getThreadId()_ – Obtains the current thread ID via GetCurrentThreadId.
+ To confirm correctness, the new FFM-based methods were compared against the existing OSHI implementation and both outputs match
```
System.out.println("below outputs from OSHI FFM");
WindowsOperatingSystemFFM ffm = new WindowsOperatingSystemFFM();
System.out.println("isElevated " + ffm.isElevated());
System.out.println("getSystemBootTime " + ffm.getSystemBootTime());
System.out.println("getThreadCount " + ffm.getThreadCount()); …
```

Add isElevated, getSystemBootTime, getThreadCount, getThreadId functions in WindowsOperatingSystemFFM

---

oshi-core/src/test/java/oshi/SystemInfoTest.java
pom.xml

Fixes failing CI:
- SystemInfoTest didn't do a length check and is failing on sublist for installed apps when the list is empty (Unix tests)
- Forbidden APIs check doesn't have jdk25 signatures yet. Temporarily skipping it in the java25 profile until they're available.

Fix failing CI
