README.md

This PR is fixing #21 
* fixed Sigar URL
* fixed Sigar licensing info

Fixed Sigar URL and note about Sigar licensing in README.md

---

CHANGELOG.md
README.md
src/main/java/oshi/hardware/HardwareAbstractionLayer.java
src/main/java/oshi/hardware/PowerSource.java
src/main/java/oshi/software/os/linux/LinuxHardwareAbstractionLayer.java
src/main/java/oshi/software/os/linux/proc/LinuxPowerSource.java
src/main/java/oshi/software/os/mac/MacHardwareAbstractionLayer.java
src/main/java/oshi/software/os/mac/local/CoreFoundation.java
src/main/java/oshi/software/os/mac/local/IOKit.java
src/main/java/oshi/software/os/mac/local/MacPowerSource.java
src/main/java/oshi/software/os/windows/WindowsHardwareAbstractionLayer.java
src/main/java/oshi/software/os/windows/nt/PowrProf.java
src/main/java/oshi/software/os/windows/nt/WindowsPowerSource.java
src/main/java/oshi/util/FormatUtil.java
src/test/java/oshi/SystemInfoTest.java
src/test/java/oshi/util/FormatUtilTest.java

Submitted for review/discussion of API structure before continuing Linux and Windows ports.
Sample output: 
Power: InternalBattery-0 (Charging) @ 96.01%, 0:55 remaining.

Battery Information

---

README.md
RELEASING.md

Update links to API and Download

---

CHANGELOG.md
RELEASING.md
pom.xml

Update RELEASING.md doc to reflect new release process

---

src/main/java/oshi/software/os/windows/nt/OSVersionInfoEx.java

Windows 10 & Windows Server 2016 (technical preview)

add support for Windows 10

---

CHANGELOG.md
README.md
RELEASING.md
pom.xml
src/main/java/oshi/hardware/package-info.java
src/main/java/oshi/package-info.java
src/main/java/oshi/software/os/OSFileStore.java
src/main/java/oshi/software/os/linux/LinuxHardwareAbstractionLayer.java
src/main/java/oshi/software/os/linux/proc/CentralProcessor.java
src/main/java/oshi/software/os/linux/proc/GlobalMemory.java
src/main/java/oshi/software/os/linux/proc/LinuxPowerSource.java
src/main/java/oshi/software/os/mac/MacHardwareAbstractionLayer.java
src/main/java/oshi/software/os/mac/local/CentralProcessor.java
src/main/java/oshi/software/os/mac/local/GlobalMemory.java
src/main/java/oshi/software/os/mac/local/MacPowerSource.java
src/main/java/oshi/software/os/mac/local/OSVersionInfoEx.java
src/main/java/oshi/software/os/package-info.java
src/main/java/oshi/software/os/windows/nt/CentralProcessor.java
src/main/java/oshi/software/os/windows/nt/GlobalMemory.java
src/main/java/oshi/software/os/windows/nt/OSNativeSystemInfo.java
src/main/java/oshi/software/os/windows/nt/OSVersionInfoEx.java
src/main/java/oshi/software/os/windows/nt/WindowsPowerSource.java
src/main/java/oshi/util/FileUtil.java
src/main/java/oshi/util/Util.java
src/test/java/oshi/SystemInfoTest.java

Add SLF4J logging and replace exceptions with log errors

---

CHANGELOG.md
README.md
src/main/java/oshi/hardware/Processor.java
src/main/java/oshi/software/os/linux/proc/CentralProcessor.java
src/main/java/oshi/software/os/mac/local/CentralProcessor.java
src/main/java/oshi/software/os/windows/nt/CentralProcessor.java
src/main/java/oshi/util/ParseUtil.java
src/test/java/oshi/SystemInfoTest.java
src/test/java/oshi/util/ParseUtilTest.java

Count logical and physical processors

---

CHANGELOG.md
README.md
UPGRADING.md
pom.xml
src/main/java/oshi/hardware/CentralProcessor.java
src/main/java/oshi/hardware/HardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
src/main/java/oshi/hardware/platform/linux/LinuxHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
src/main/java/oshi/hardware/platform/mac/MacHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
src/main/java/oshi/hardware/platform/windows/WindowsHardwareAbstractionLayer.java
src/main/java/oshi/jna/platform/linux/Libc.java
src/main/java/oshi/jna/platform/linux/package-info.java
src/main/java/oshi/jna/platform/mac/CoreFoundation.java
src/main/java/oshi/jna/platform/mac/IOKit.java
src/main/java/oshi/jna/platform/mac/package-info.java
src/main/java/oshi/jna/platform/windows/Kernel32.java
src/main/java/oshi/jna/platform/windows/Pdh.java
src/main/java/oshi/jna/platform/windows/PowrProf.java
src/main/java/oshi/jna/platform/windows/package-info.java
src/test/java/oshi/SystemInfoTest.java

Switch Processor to singular object

---

.travis.yml
CHANGELOG.md
README.md
pom.xml
src/main/java/oshi/hardware/Display.java
src/main/java/oshi/hardware/HardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/linux/LinuxDisplay.java
src/main/java/oshi/hardware/platform/linux/LinuxHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/mac/MacDisplay.java
src/main/java/oshi/hardware/platform/mac/MacHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/windows/WindowsDisplay.java
src/main/java/oshi/hardware/platform/windows/WindowsHardwareAbstractionLayer.java
src/main/java/oshi/util/EdidUtil.java
src/main/java/oshi/util/ExecutingCommand.java
src/main/java/oshi/util/ParseUtil.java
src/test/java/oshi/SystemInfoTest.java
src/test/java/oshi/util/ParseUtilTest.java

Add Display Info using EDID

---

src/main/java/oshi/hardware/HardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
src/main/java/oshi/util/ExecutingCommand.java

Fix NPE on no vendor_id.

---

CHANGELOG.md
README.md
pom.xml
src/main/java/oshi/hardware/platform/windows/WindowsGlobalMemory.java

Memory information wasn't updating for Windows

---

CHANGELOG.md
README.md
src/main/java/oshi/hardware/CentralProcessor.java
src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
src/main/java/oshi/jna/platform/mac/SystemB.java
src/test/java/oshi/SystemInfoTest.java

Also expanded load average to get all 3 system values

Add IOWait and IRQ ticks

---

src/main/java/oshi/hardware/Disks.java
src/main/java/oshi/hardware/HWDiskStore.java
src/main/java/oshi/hardware/HardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/linux/LinuxBlockDevStats.java
src/main/java/oshi/hardware/platform/linux/LinuxDisks.java
src/main/java/oshi/hardware/platform/linux/LinuxHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/mac/MacDisks.java
src/main/java/oshi/hardware/platform/mac/MacHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
src/main/java/oshi/hardware/platform/windows/WindowsHardwareAbstractionLayer.java
src/main/java/oshi/jna/platform/linux/Udev.java
src/test/java/oshi/SystemInfoTest.java

For creating this pull request, I've used the same logic for File System information extract

Added disk information and statistics

---

CHANGELOG.md
README.md
src/main/java/oshi/jna/platform/mac/SystemB.java
src/main/java/oshi/jna/platform/windows/Kernel32.java
src/main/java/oshi/software/os/OSFileStore.java
src/main/java/oshi/software/os/linux/LinuxFileSystem.java
src/main/java/oshi/software/os/mac/MacFileSystem.java
src/main/java/oshi/software/os/windows/WindowsFileSystem.java
src/test/java/oshi/SystemInfoTest.java

In progress. MacOS done.  #146

Add File System Types

---

src/main/java/oshi/hardware/platform/linux/LinuxSensors.java

Fix infinite loop when getting Linux fan speeds

---

src/main/java/oshi/hardware/HardwareAbstractionLayer.java
src/main/java/oshi/hardware/Networks.java
src/main/java/oshi/hardware/common/AbstractHardwareAbstractionLayer.java
src/main/java/oshi/hardware/common/AbstractNetworks.java
src/main/java/oshi/hardware/platform/linux/LinuxHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/linux/LinuxNetworks.java
src/main/java/oshi/hardware/platform/mac/MacHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/mac/MacNetworks.java
src/main/java/oshi/hardware/platform/windows/WindowsHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/windows/WindowsNetworks.java
src/main/java/oshi/hardware/stores/HWNetworkStore.java
src/test/java/oshi/SystemInfoTest.java

This code implements (partially for all systems and extensively for Linux) issue #138

 Added network interfaces information and statistics

---

src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
src/main/java/oshi/hardware/platform/windows/WindowsSensors.java
src/main/java/oshi/jna/platform/windows/COM/EnumWbemClassObject.java
src/main/java/oshi/jna/platform/windows/COM/WbemClassObject.java
src/main/java/oshi/jna/platform/windows/COM/WbemLocator.java
src/main/java/oshi/jna/platform/windows/COM/WbemServices.java
src/main/java/oshi/jna/platform/windows/COM/package-info.java
src/main/java/oshi/jna/platform/windows/Ole32.java
src/main/java/oshi/software/os/FileSystem.java
src/main/java/oshi/util/platform/windows/WmiUtil.java

Initial commit is a working example.  TODO over the next few days is to implement existing methods using this.

Switch WMI queries to use COM

---

src/main/java/oshi/jna/platform/windows/Ole32.java
src/main/java/oshi/util/platform/windows/WmiUtil.java
src/test/java/oshi/SystemInfoTest.java

Enable better WMI COM multithreading

---

src/main/java/oshi/hardware/platform/linux/LinuxSensors.java
src/main/java/oshi/util/FileUtil.java

Add fallback Linux temperature sensor reading

---

CHANGELOG.md
README.md
src/main/java/oshi/hardware/HardwareAbstractionLayer.java
src/main/java/oshi/hardware/UsbDevice.java
src/main/java/oshi/hardware/common/AbstractHardwareAbstractionLayer.java
src/main/java/oshi/hardware/common/AbstractUsbDevice.java
src/main/java/oshi/hardware/platform/linux/LinuxHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/linux/LinuxUsbDevice.java
src/main/java/oshi/hardware/platform/mac/MacDisplay.java
src/main/java/oshi/hardware/platform/mac/MacHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/mac/MacUsbDevice.java
src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
src/main/java/oshi/hardware/platform/windows/WindowsHardwareAbstractionLayer.java
src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java
src/main/java/oshi/util/FileUtil.java
src/main/java/oshi/util/ParseUtil.java
src/main/java/oshi/util/platform/mac/CfUtil.java
src/test/java/oshi/SystemInfoTest.java

Add USB Device listing

---

CHANGELOG.md
src/main/java/oshi/software/os/linux/LinuxOSVersionInfoEx.java
src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Improve Linux OS version parsing

---

CHANGELOG.md
src/main/java/oshi/hardware/UsbDevice.java
src/main/java/oshi/hardware/common/AbstractUsbDevice.java
src/main/java/oshi/hardware/platform/linux/LinuxUsbDevice.java
src/main/java/oshi/hardware/platform/mac/MacUsbDevice.java
src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java
src/main/java/oshi/jna/platform/linux/Udev.java
src/main/java/oshi/jna/platform/mac/IOKit.java

Add VendorID and ProductID to UsbDevice

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacDisks.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java

Streamlined macOS FileSystem

---

CHANGELOG.md
UPGRADING.md
oshi-core/pom.xml
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-json/pom.xml
oshi-json/src/main/java/oshi/json/hardware/CentralProcessor.java
oshi-json/src/main/java/oshi/json/hardware/impl/CentralProcessorImpl.java
oshi-json/src/test/java/oshi/json/SystemInfoTest.java
pom.xml

Combine IOwait and IRQ ticks into processor tick array

---

.gitignore
oshi-core/pom.xml
oshi-json/pom.xml
pom.xml
src/site/site.xml

@dbwiddis I didn't fix the scm issues here just ran sort to get the spacing proper per maven standards, updated slf4j, updated some plugins, and fixed the relative path issue.  I think at this point you have two tasks to complete.
- Create separate 'oshi-assembly' and move things there for that.
- Add scm to the underlying modules (all of them and they are identical)

Clean up build

---

oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java

Prevent endless loop if identifier and components are both null

---

oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisDisks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisPowerSource.java
oshi-core/src/main/java/oshi/jna/platform/unix/solaris/LibKstat.java
oshi-core/src/main/java/oshi/jna/platform/unix/solaris/package-info.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisFileSystem.java
oshi-core/src/main/java/oshi/util/platform/unix/solaris/KstatUtil.java
oshi-core/src/main/java/oshi/util/platform/unix/solaris/package-info.java

Get Kstat programmatically

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Fix exceptions on windows disks/partitions

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworks.java
oshi-core/src/main/java/oshi/jna/platform/windows/IPHlpAPI.java

Make Windows network statistics 64-bit

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/HWDiskStore.java
oshi-core/src/main/java/oshi/hardware/HWPartition.java
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacDisks.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdDisks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisDisks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworks.java
oshi-core/src/main/java/oshi/jna/platform/windows/IPHlpAPI.java
oshi-core/src/test/java/oshi/hardware/DisksTest.java
oshi-core/src/test/java/oshi/hardware/NetworksTest.java
oshi-json/src/main/java/oshi/json/hardware/HWDiskStore.java
oshi-json/src/main/java/oshi/json/hardware/NetworkIF.java
oshi-json/src/main/java/oshi/json/hardware/impl/HardwareAbstractionLayerImpl.java
oshi-json/src/test/java/oshi/json/hardware/DisksTest.java
oshi-json/src/test/java/oshi/json/hardware/NetworksTest.java
oshi-json/src/test/resources/oshi.json.properties

Add timestamps to disk and network IO stats

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java

Persist boot time internally on OSX and FreeBSD

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacDisks.java
oshi-core/src/main/java/oshi/jna/platform/mac/DiskArbitration.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/platform/mac/CfUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Properly handle CoreStorage Volumes on OSX

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java

Use DeviceID to link Windows Disks and Partitions

---

oshi-core/src/main/java/oshi/hardware/Assembly.java
oshi-core/src/main/java/oshi/hardware/Firmware.java
oshi-core/src/main/java/oshi/hardware/HardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/common/AbstractAssembly.java
oshi-core/src/main/java/oshi/hardware/common/AbstractFirmware.java
oshi-core/src/main/java/oshi/hardware/common/AbstractHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxAssembly.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxFirmware.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacAssembly.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacFirmware.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdAssembly.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdFirmware.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisAssembly.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisFirmware.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsAssembly.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsFirmware.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsHardwareAbstractionLayer.java
oshi-core/src/test/java/oshi/SystemInfoTest.java

Hi,
here is a first draft for the interfaces and the Windows implementation.
On Linux and Mac I have put a comment in the files which data in which fields I would copy. (Sorry - I don't have a development system on Linux or Mac)
I think it's ok if not all fields are filled on all systems. 
Greetings
Thomas

BIOS and manufacturer information for Windows/Linux/macOS

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSVersionInfoEx.java

Get Windows version from WMI

---

oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java

Remove incorrect IOWait counter from WindowsCentralProcessor

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacDisks.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSVersionInfoEx.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Rebrand Mac OS 10.12+ as macOS

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxProcess.java

Reduce required calculations for LinuxProcess initialization

---

oshi-core/src/main/java/oshi/hardware/HWDiskStore.java
oshi-core/src/main/java/oshi/hardware/HWPartition.java

Null-check Disk Store and Partition strings in setter

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworks.java
oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java

WinXP compatibility fixes

---

oshi-core/src/main/java/oshi/jna/platform/windows/Ole32.java
oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java

Don't uninitialize COM if it was initialized externally

---

oshi-core/src/test/java/oshi/hardware/DisksTest.java
oshi-json/src/test/java/oshi/json/hardware/DisksTest.java

Fix DisksTest to remove null checks

---

oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/jna/platform/unix/CLibrary.java
oshi-core/src/main/java/oshi/util/FileUtil.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-json/src/main/java/oshi/json/hardware/CentralProcessor.java

Javadoc fixes

---

oshi-core/pom.xml
oshi-core/src/main/java/oshi/hardware/Disks.java
oshi-core/src/main/java/oshi/hardware/Display.java
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/Networks.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
oshi-core/src/main/java/oshi/util/FormatUtil.java
oshi-core/src/main/java/oshi/util/MapUtil.java
oshi-core/src/main/java/oshi/util/platform/mac/CfUtil.java
oshi-core/src/test/java/oshi/util/MapUtilTest.java

Remove dependency on streamsupport

---

oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworks.java
oshi-core/src/main/java/oshi/util/FileUtil.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/FileUtilTest.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Wrap around unsigned longs in NetworkIF

---

oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSSystemInfo.java
oshi-core/src/main/java/oshi/util/ExecutingCommand.java
oshi-core/src/main/java/oshi/util/Util.java

Less stack traces

---

CHANGELOG.md
oshi-core/src/main/java/oshi/jna/platform/mac/SystemB.java
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/java/oshi/util/LsofUtil.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java
oshi-json/src/main/java/oshi/json/software/os/OSProcess.java
oshi-json/src/test/java/oshi/json/software/os/OperatingSystemTest.java
oshi-json/src/test/resources/oshi.json.properties

Process Current Working Directory

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-json/src/test/java/oshi/json/SystemInfoTest.java

adding in cpu steal tick type for linux systems

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java

- added additional path for reading temperature
Signed-off-by: Christoph Weitkamp <github.christophweitkamp.de>

Linux sensors update for reading temperature

---

oshi-core/pom.xml
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxBlockDevStats.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdDisks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisDisks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
oshi-core/src/main/java/oshi/software/common/AbstractNetworkParams.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxNetworkParams.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSVersionInfoEx.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacNetworkParams.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOSVersionInfoEx.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsNetworkParams.java
oshi-core/src/main/java/oshi/util/FileUtil.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Create pattern for whitespace and use it in Linux implementation.

Performance improvement on regex reuse

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-json/src/main/java/oshi/json/software/os/OperatingSystem.java
oshi-json/src/main/java/oshi/json/software/os/impl/OperatingSystemImpl.java

Fix NPE for processes terminating before iteration.

---

oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java

Fixed unchecked exception ClassCastException thrown by the IBM JVM when executing the MXBean detection method

Added unchecked exception to MXBean detection method

---

oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java

Catch error on OS Command line length

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworks.java

Fix version check in WindowsNetworks

---

README.md

Simple change. This project has helped me immensely compared to Sigar.

Add sys-API to Projects using OSHI

---

pom.xml

Payara team discovered OSGi issues in Oshi when trying to use it in Payara
Thanks for incorporating

added com.sun.jna.* packages to fix OSGi issues

---

CHANGELOG.md
oshi-core/pom.xml
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/jna/platform/mac/SystemB.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/hardware/CentralProcessorTest.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java
oshi-json/src/test/java/oshi/json/hardware/CentralProcessorTest.java

Implement context switches and interrupts on macOS, FreeBSD, Solaris

---

oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-json/src/main/java/oshi/json/software/os/OSProcess.java

Don't iterate over lsof

---

oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java

Improve WMIUtil logging

---

oshi-core/src/main/java/oshi/hardware/HWDiskStore.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacDisks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdDisks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisDisks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java

I used a similar approach to NetworkIF.updateNetworkStats, and implemented the update methods for each platform to the best of my ability.
NB: untested, but the changes are really just *moving* existing code rather than adding anything especially new, so in most cases should be fairly low risk.  I can test it on Windows, Linux, and FreeBSD fairly easily but don't have access to Mac or Solaris for testing those.

Added HWDiskStore.updateDiskStats

---

oshi-core/src/main/java/oshi/util/platform/unix/solaris/KstatUtil.java

Synchronize access to KstatCtl variable

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/GlobalMemory.java
oshi-core/src/main/java/oshi/hardware/common/AbstractGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGlobalMemory.java
oshi-core/src/test/java/oshi/hardware/GlobalMemoryTest.java
oshi-json/src/main/java/oshi/json/hardware/GlobalMemory.java
oshi-json/src/main/java/oshi/json/hardware/HWDiskStore.java
oshi-json/src/main/java/oshi/json/hardware/impl/GlobalMemoryImpl.java
oshi-json/src/test/java/oshi/json/hardware/GlobalMemoryTest.java
oshi-json/src/test/resources/oshi.json.properties

Expose memory page size to API.

---

oshi-core/src/main/java/oshi/hardware/HWDiskStore.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
oshi-core/src/main/java/oshi/jna/platform/windows/Pdh.java
oshi-core/src/main/java/oshi/util/platform/windows/PdhUtil.java

Windows portion of #510. Continues to address #505.

Switch Windows disk updates to use PDH counters

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java

Use Disk Store's hashCode as key for update map.

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java
oshi-json/src/main/java/oshi/json/software/os/OperatingSystem.java
oshi-json/src/main/java/oshi/json/software/os/impl/OperatingSystemImpl.java
oshi-json/src/test/java/oshi/json/software/os/OperatingSystemTest.java
oshi-json/src/test/resources/oshi.json.properties

Add OS Bitness

---

oshi-core/src/main/java/oshi/hardware/HWDiskStore.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java

Fixes memory leak reported in #521

Unreference udev device and handle. 

---

oshi-core/src/test/java/oshi/util/EdidUtilTest.java

Remove dependency on javax.xml.bind.DatatypeConverter.

---

oshi-core/src/main/java/oshi/util/EdidUtil.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/EdidUtilTest.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java
oshi-json/src/main/java/oshi/json/hardware/impl/DisplayImpl.java

Fixes #523 (for real this time)

Remove DataTypeConverter dependency so OSHI builds on Java 9

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/platform/windows/PerfDataUtil.java

Localize PDH Counter paths

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java
oshi-json/src/main/java/oshi/json/software/os/OSProcess.java
oshi-json/src/test/java/oshi/json/software/os/OperatingSystemTest.java

Optimize Process CPU Sort

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Catch Win32Exception on process path race condition

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGlobalMemory.java

Don't get PDH swap stats if no swap

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Windows process uptime wasn't updating

---

oshi-core/src/main/java/oshi/software/os/OSProcess.java

Fix OSProcess uptime multicore bug

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Fix proc stat parsing on older Linux distros

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsNetworkParams.java

Remove unneeded debug query and fix a WMI cast error

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/util/platform/linux/ProcUtil.java

Fix calculation of Hz on Linux

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java

Catch exception when english counters missing

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Catches exceptions in #642 and #643 and provides better log messages.

Better error handling of registry permission/language issues

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java

Fix Windows idle counter calculation

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsSoundCard.java

- fix typo

---

oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdSoundCard.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

FreeBSD sound card implementation.
Also have added another method inside ParseUtil.

Freebsd sound card

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsSensors.java

Fix WMI type of Win32_Processor CurrentVoltage

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfDataUtil.java

Recreate counter handles when invalid

---

oshi-core/pom.xml

Fixes #669 (doesn't actually fix but reduces the probability of a problem)

Include jna dependencies at higher level

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisNetworks.java

Solaris 10 network stats compatibility fix

---

CHANGELOG.md
oshi-core/src/main/java/oshi/jna/platform/unix/CLibrary.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Fix Linux proc stat and pagesize parsing

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-json/src/main/java/oshi/json/software/os/OperatingSystem.java
oshi-json/src/main/java/oshi/json/software/os/impl/OperatingSystemImpl.java

Optionally skip slow OSProcess fields

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSVersionInfoEx.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Prioritize system-release for Fedora and CentOS version

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Cache OSProcesses on Linux

---

oshi-core/src/main/java/oshi/util/FileUtil.java

We use it frequently so that application can not afford the LOGGIN file every time.

! LOGGING when enable the level

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/Util.java
oshi-core/src/test/java/oshi/util/UtilTest.java

Changes in order to have a Unique Computer Identifier in the Util method and test the same in the UtilTest method.

Uci util method

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/platform/windows/PerfDataUtil.java

Fixes #662 since the beast of a commit #666 didn't do it right

Fix PerfData error handling

---

oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdSoundCard.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisSoundCard.java

Removed unnecessary 'continues' and merged similiar 'continue' conditions into one for better readability.
Closes #700

Refined control logic in Solaris/FreeBsd Soundcard

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsSensors.java

Fix WMI type for Fan DesiredSpeed

---

oshi-core-shaded/pom.xml
oshi-core/pom.xml
oshi-dist/pom.xml
oshi-json/pom.xml
pom.xml

Make license header path accessible to submodules

---

oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java

I have done the minimum to solved the NPE described by the issue #719 
I wasn't able to create a unit test.
And because the underlying problem is not systematic, I haven't still see any changes.

Better handling of null hresult in COMException

---

pom.xml

Update pom.xml versions

---

oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java

Document that the Windows Management Interface needs Windows.

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGlobalMemory.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfDataUtil.java

Fix buggy handling of memory counter failed update

---

CHANGELOG.md
README.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
src/site/markdown/README.md

Fix Windows process token handle leak

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/platform/windows/WmiQueryHandler.java

Redundant COM initialization still needs uninitialization

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisks.java

Prevent exception in WindowsDisks initializer

---

oshi-core/src/main/java/oshi/hardware/ComputerSystem.java
oshi-core/src/main/java/oshi/hardware/Firmware.java
oshi-core/src/main/java/oshi/hardware/common/AbstractBaseboard.java
oshi-core/src/main/java/oshi/hardware/common/AbstractComputerSystem.java
oshi-core/src/main/java/oshi/hardware/common/AbstractFirmware.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxBaseboard.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxFirmware.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdBaseboard.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdFirmware.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsBaseboard.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsFirmware.java
oshi-core/src/main/java/oshi/util/Constants.java
oshi-core/src/main/java/oshi/util/ParseUtil.java

Work in progress, opening the PR to get the automated testing and static code review with each commit.

API overhaul - ComputerSystem, Baseboard, and Firmware

---

oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/jna/platform/windows/Kernel32.java
oshi-core/src/main/java/oshi/jna/platform/windows/Kernel32Util.java
oshi-core/src/main/java/oshi/jna/platform/windows/WinNT.java
oshi-dist/src/assembly/assembly.xml
pom.xml

Processor counting in Processor Groups

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/jna/platform/windows/Kernel32Util.java
oshi-core/src/main/java/oshi/jna/platform/windows/ProcInfo.java
oshi-core/src/main/java/oshi/jna/platform/windows/WinNT.java

Set up for Numa Node counting

---

CHANGELOG.md
oshi-core/src/main/java/oshi/data/windows/PerfCounterQuery.java
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java

Assign Logical Processors to NUMA nodes

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsSoundCard.java

Get Windows Sound Card info from registry

---

UPGRADING.md
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/common/AbstractNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsSoundCard.java
oshi-core/src/test/java/oshi/hardware/NetworksTest.java

Remove Mac netIF cache

---

oshi-core/src/main/java/oshi/data/windows/PerfCounterQuery.java

Modify PerfCounterQuery.java file.
Make changes in line 109 change getDeclarClass I changed the function to getClass.

Solve issue#803

---

oshi-core/src/main/java/oshi/data/windows/PerfCounterQuery.java

Removed validation check for PdhCounterProperty in the constructor. See
discussion of issue #806 for details.

#806: Removed ineffective type checking.

---

oshi-core/src/main/java/oshi/software/os/OSFileStore.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisFileSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java
oshi-core/src/test/java/oshi/software/os/FileSystemTest.java

Separate Free and Usable space on Filestores

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Fixes #833 StringIndexOutOfBoundsException

issue-833 - Fixing StringIndexOutOfBoundsException

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

Solves #843 Wrong time unit used in LinuxCentralProcessor

#843: Convert Jiffies to Milliseconds

---

oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java

Change log message when Mac procargs call fails

---

oshi-demo/src/main/java/oshi/demo/DetectVM.java
oshi-demo/src/test/java/oshi/demo/DetectVMTest.java

I refer to genMAC method on https://github.com/docker/libnetwork/blob/master/netutils/utils.go

Add vm mac address for Docker container.

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java

To ignore overlay filesystem (Linux)

To ignore overlay filesystem (Linux)

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

WTSEnumerateProcessesEx need minimum window 7

WTSEnumerateProcessesEx need minimum window 7

---

CHANGELOG.md
appveyor.yml
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java

Attempted to address bug in physical processor count for linux and unix. Still needs to be tested.

Physical processor count fix

---

oshi-demo/src/main/java/oshi/demo/DetectVM.java

Thank you for giving a first timer a chance.

Fixed Issue #908, now empty string also checked.

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java
oshi-core/src/test/java/oshi/hardware/SensorsTest.java

Changed filename for sensor to full path. #854
Changed unit test for sensors (based on availability of sys/class path)

Fixed reading of sensor data

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java

Don't use NPE for loop control

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/HardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/UsbDevice.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/common/AbstractUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacDisks.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdSoundCard.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisSoundCard.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/java/oshi/util/platform/mac/CfUtil.java
oshi-core/src/main/java/oshi/util/platform/mac/IOKitUtil.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/hardware/UsbDeviceTest.java

Remove internal caches

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

Process bitness

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacSensors.java
oshi-core/src/main/java/oshi/util/platform/mac/SmcUtil.java
oshi-dist/src/main/resources/eclipse/OSHI Java Conventions.xml

Fix SMC datatype reading

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxBaseboard.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxFirmware.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/platform/linux/ProcUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Raspberry Pi compatibility fixes

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

Add isElevated method

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractFirmware.java
oshi-core/src/main/java/oshi/hardware/common/AbstractGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/common/AbstractVirtualMemory.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/hardware/ComputerSystemTest.java
oshi-core/src/test/java/oshi/hardware/GlobalMemoryTest.java
oshi-core/src/test/java/oshi/hardware/VirtualMemoryTest.java

Added toString implementations for GlobalMemory,VirtualMemory and Firmware
Fixes #945

Added toString implementations for GlobalMemory,VirtulMemory and Firmware

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractPowerSource.java
oshi-core/src/test/java/oshi/SystemInfoTest.java

PowerSource toString method as specified in issue #942

Added toString implementation to PowerSource

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Fixes #954 
Cut-and-pasted all overloaded methods as identified on https://www.codefactor.io/repository/github/oshi/oshi/issues/master?category=Style&groupId=787

Moved overloaded methods together

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxVirtualMemory.java

Commited changes in 
oshi-core\src\main\java\oshi\hardware\platform\linux\LinuxGlobalMemory.java:162
oshi-core\src\main\java\oshi\hardware\platform\linux\LinuxVirtualMemory.java:128
converted 0l to 0L;

Solved #955

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/Constants.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/platform/windows/WmiUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Properly handle null WMI DateTime results

---

oshi-core/src/test/java/oshi/util/MemoizerTest.java

Logic tweaks and ample comments for clarity.  @stIncMale please review!

Memoizer test updates and comments

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java

Update for variable length diskstats

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java

Exclude Docker shm mounts from FileSystem list

---

.travis.yml
appveyor.yml
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxPowerSource.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacSensors.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsDisplay.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/platform/mac/SmcUtil.java

Catch up 3.13.x branch with bugfixes from 4.0.x

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/java/oshi/util/platform/windows/WmiQueryHandler.java
oshi-demo/pom.xml
pom.xml

Logging improvements based on #996

Add hresult to COM error logging

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Fix boot time calculation

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java

Thank you for this opportunity! I look forward to hearing from you soon!
Fixes #1015

created thread-safe lazy initialization using Memoizer class

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Fix for https://github.com/oshi/oshi/issues/1019

Fix bitness query

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java

Prefer vcgencmd on Raspberry Pi when available

---

oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

More control of getProcess latency

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/resources/oshi.properties

Configure event log name and fallback on failure to read

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxGlobalMemory.java

Fix Linux page size calculation

---

oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java

Catch PDHexception on object initialization

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Fixes #1055 (except for log output)

Check systemctl for stopped services

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Restore Linux build number parsing

---

.gitattributes

General good practice to have a gitattribute file.  This is a default github puts together.  I've been sitting on this for a while :)

[git] Add gitattributes file

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Don't read past allocated buffer for string

---

FAQ.md
README.md
oshi-core/pom.xml

Best effort at resolving or documenting JNA dependency issues

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/common/AbstractFileSystem.java
oshi-core/src/main/java/oshi/software/os/FileSystem.java
oshi-core/src/main/java/oshi/software/os/OSFileStore.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisFileSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/software/os/FileSystemTest.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Initial version. Please check and verify ... did not even test it yet ...

Implement option to gather only local filestore stats.

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/OSFileStore.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisFileSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java
oshi-core/src/test/java/oshi/software/os/FileSystemTest.java

Get FileStore options

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisNetworks.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworks.java
oshi-core/src/test/java/oshi/hardware/NetworksTest.java

Add network interface dropped packets and collisions

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java

Handle null return from udev_device_get_devnode

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java

Fix infinite loop and handle leak in LinuxDisks

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/proc/DiskStats.java
oshi-core/src/main/java/oshi/driver/linux/proc/package-info.java

Add utility to fetch proc/diskstats

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/proc/ProcessStat.java
oshi-core/src/main/java/oshi/driver/windows/registry/HkeyPerformanceDataUtil.java

Driver for Process stats

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32LogicalDisk.java
oshi-core/src/main/java/oshi/software/os/OSFileStore.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisFileSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java
oshi-core/src/test/java/oshi/software/os/FileSystemTest.java

Add Volume Label to OSFileStore

---

CHANGELOG.md
oshi-demo/pom.xml
oshi-demo/src/main/java/oshi/demo/OshiGui.java
oshi-demo/src/main/java/oshi/demo/gui/Config.java
oshi-demo/src/main/java/oshi/demo/gui/FileStorePanel.java
oshi-demo/src/main/java/oshi/demo/gui/MemoryPanel.java
oshi-demo/src/main/java/oshi/demo/gui/OsHwTextPanel.java
oshi-demo/src/main/java/oshi/demo/gui/OshiJPanel.java
oshi-demo/src/main/java/oshi/demo/gui/ProcessPanel.java
oshi-demo/src/main/java/oshi/demo/gui/ProcessorPanel.java
oshi-demo/src/main/java/oshi/demo/gui/UsbPanel.java
pom.xml

Demo Swing GUI

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java
oshi-demo/src/main/java/oshi/demo/OshiGui.java
oshi-demo/src/main/java/oshi/demo/OshiHTTPServer.java
oshi-demo/src/main/java/oshi/demo/gui/Config.java
oshi-demo/src/main/java/oshi/demo/gui/FileStorePanel.java
oshi-demo/src/main/java/oshi/demo/gui/MemoryPanel.java
oshi-demo/src/main/java/oshi/demo/gui/OsHwTextPanel.java
oshi-demo/src/main/java/oshi/demo/gui/OshiJPanel.java
oshi-demo/src/main/java/oshi/demo/gui/ProcessPanel.java
oshi-demo/src/main/java/oshi/demo/gui/ProcessorPanel.java
oshi-demo/src/main/java/oshi/demo/gui/UsbPanel.java

Add Process usage between ticks

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32VideoController.java
oshi-core/src/main/java/oshi/hardware/GraphicsCard.java
oshi-core/src/main/java/oshi/hardware/HardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/common/AbstractGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/common/AbstractGraphicsCard.java
oshi-core/src/main/java/oshi/hardware/common/AbstractHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/common/AbstractSoundCard.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxGraphicsCard.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacGraphicsCard.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacSoundCard.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdGraphicsCard.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisGraphicsCard.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisUsbDevice.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGraphicsCard.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsHardwareAbstractionLayer.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java
oshi-core/src/main/java/oshi/software/common/AbstractFileSystem.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/hardware/GraphicsCardTest.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Get Graphics Cards

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Linux proc symlinks may show as (deleted) (#1153)

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisks.java

Fix handle leak in LinuxDisks

---

oshi-core/src/main/java/oshi/annotation/concurrent/Immutable.java
oshi-core/src/main/java/oshi/annotation/concurrent/NotThreadSafe.java
oshi-core/src/main/java/oshi/annotation/concurrent/ThreadSafe.java

Add annotations in oshi.annotation.concurrent package

Add annotations @Documented

---

oshi-core/src/main/java/oshi/util/platform/unix/solaris/KstatUtil.java

This pull request adds the `final` annotation to the class.

Add final annotation to class

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/unix/solaris/kstat/SystemPages.java
oshi-core/src/main/java/oshi/driver/unix/solaris/kstat/package-info.java
oshi-core/src/main/java/oshi/hardware/VirtualMemory.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxVirtualMemory.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacVirtualMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdVirtualMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisVirtualMemory.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsVirtualMemory.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/hardware/VirtualMemoryTest.java

Add more VirtualMemory information

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsVirtualMemory.java

Correct virtual memory in use on Windows

---

CHANGELOG.md
oshi-core/src/main/java/oshi/annotation/concurrent/GuardedBy.java
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32ProcessCached.java
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java
oshi-core/src/main/resources/oshi.properties

Optionally batch WMI command line queries

---

pom.xml

Enable Nexus Staging Plugin

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxHWDiskStore.java
oshi-core/src/main/java/oshi/jna/platform/linux/Udev.java

Fix NPE on no partitions

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java

Use path for Linux mountpoint

---

oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java

Fix NPE on OSProcess

---

oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java

I've tried to fix #1205 as you've explained.
I have declared a boolean variable before the for loop at line 155 and added an if statement after the for loop, to check if the boolean is still false. And also I've replaced break at 296 with boolean true.
Please check if this is correct.
Thanks.

Fixed leak in WindowsPowerSource

---

CHANGELOG.md
oshi-core/src/test/java/oshi/hardware/GraphicsCardTest.java

This is my first attempt at contributing to an open source project, even though it's only test messages if anyone has any feedback I'd be happy to hear!

 (Issue #1215) Added messages to unit test assertions in GraphicsCardTest.java

---

oshi-core/src/test/java/oshi/hardware/ComputerSystemTest.java

This is my first attempt in contributing to opensource. would be happy for any feedback  :)

Add messages to unit test assertions in ComputerSystemTest.java

---

CHANGELOG.md
oshi-core/src/test/java/oshi/hardware/DisksTest.java
oshi-core/src/test/java/oshi/hardware/DisplayTest.java

extended the assertion methods for DisksTest.java & DisplayTest.java by explanation messages. 
https://github.com/oshi/oshi/issues/1215

Add junit message for DisksTest.java & DisplayTest.java

---

CHANGELOG.md
oshi-core/src/test/java/oshi/hardware/CentralProcessorTest.java

Added tests messages in CentralProcessorTest.java. Might be a bit too long and convoluted in some places, but I think they do the trick.

Added messages for Central Processor's unit tests

---

CHANGELOG.md
oshi-core/src/test/java/oshi/hardware/GlobalMemoryTest.java

Contributed to issue #1215. Please let me know if you have any feedback!

Add messages to unit tests in GlobalMemoryTest.Java

---

.github/FUNDING.yml

I believe this will add a proper sponsor button to this repo. Please double check the package name for me. Inspired by [ruby-grape](https://github.com/ruby-grape/grape/blob/master/.github/FUNDING.yml).

Add a Sponsor button.

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/proc/ProcessStat.java
oshi-core/src/main/java/oshi/util/platform/linux/ProcPath.java

Add a driver for proc/pid/statm

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java

Fix calculation of Linux process start time

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/FileUtil.java

Fallback to read properties file from classloader of the class

---

oshi-core/src/main/java/oshi/driver/linux/Devicetree.java
oshi-core/src/main/java/oshi/driver/linux/Dmidecode.java
oshi-core/src/main/java/oshi/driver/linux/Lshal.java
oshi-core/src/main/java/oshi/driver/linux/Lshw.java
oshi-core/src/main/java/oshi/driver/linux/Sysfs.java
oshi-core/src/main/java/oshi/driver/linux/proc/CpuInfo.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxComputerSystem.java

Refactor LinuxComputerSystem to drivers

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/registry/HkeyPerformanceDataUtil.java
oshi-core/src/main/java/oshi/driver/windows/registry/ProcessPerformanceData.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java

More accurate process start times

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32LogicalDiskToPartition.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsHWDiskStore.java

I modified WindowsHWDiskStore to fix that get logical partition on windows correctly, but all the logical partitions are same size, I have
not found a method to correct it

get logical partition on windows correctly

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java

Use fragment size in Linux FileStore size calculation

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/registry/HkeyPerformanceDataUtil.java
oshi-core/src/main/java/oshi/driver/windows/registry/ProcessPerformanceData.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/resources/oshi.properties

Avoid NPE for failed Windows registry counter size

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java

Fix Raspberry Pi sensor parsing

---

oshi-core/src/test/java/oshi/hardware/PowerSourceTest.java
oshi-core/src/test/java/oshi/hardware/SensorsTest.java
oshi-core/src/test/java/oshi/hardware/SoundCardTest.java
oshi-core/src/test/java/oshi/hardware/UsbDeviceTest.java
oshi-core/src/test/java/oshi/hardware/VirtualMemoryTest.java

Added messages for unit test assertions for remaining classes in oshi-core/src/test/java/oshi/hardware/ 
as per #1215

Added messages for unit test assertions

---

.travis.yml
CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java
oshi-core/src/main/java/oshi/software/os/mac/MacInternetProtocolStats.java
oshi-core/src/main/java/oshi/util/platform/mac/SysctlUtil.java

Allow variable size structs for macOS IP stat sysctl calls

---

oshi-core/src/test/java/oshi/hardware/PowerSourceTest.java
oshi-core/src/test/java/oshi/hardware/SensorsTest.java
oshi-core/src/test/java/oshi/hardware/VirtualMemoryTest.java
oshi-core/src/test/java/oshi/software/os/FileSystemTest.java
oshi-core/src/test/java/oshi/software/os/InternetProtocolStatsTest.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

Update test assertions for classes in the oshi-core/src/test/software.os
package.
Refs #1215

Add messages to unit test assertions

---

oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/util/EdidUtilTest.java
oshi-core/src/test/java/oshi/util/ExecutingCommandTest.java
oshi-core/src/test/java/oshi/util/FileUtilTest.java
oshi-core/src/test/java/oshi/util/FormatUtilTest.java

I've added some messages to unit test assertions as per #1215.
Honestly I got bored after this bit, however I don't see myself able to contribute to the other Issues...

Add messages to unit test assertions.

---

oshi-core/src/test/java/oshi/util/UtilTest.java

added unit test message

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Reduce log level for expected Windows permission failures

---

oshi-core/src/test/java/oshi/util/GlobalConfigTest.java

Addition of assertion messages for GlobalConfigTest, encapsulated in the GlobalConfigAsserter class. #1215 Feedback would much appreciated.

Addition of assertion messages for GlobalConfigTest

---

oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Add Assert messages to ParseUtilTest

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java

Vendor frequency from non-Intel chips

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

Fix redundant multiplication in Linux max Freq

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java

Make Windows System CPU usage Process-group aware

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxDisplay.java
oshi-core/src/main/java/oshi/util/ExecutingCommand.java

Don't use localized environment for xrandr

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

Retry Linux CPU proc stats once on failure

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java

Adapt to macOS 11 version reverse compatibility

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/mac/net/NetStat.java

Handle macOS unsigned byte ifTypes

---

CHANGELOG.md
FAQ.md
PERFORMANCE.md
README.md
oshi-core/src/main/java/oshi/util/platform/windows/WmiQueryHandler.java
oshi-demo/src/main/java/oshi/demo/UserComInit.java
oshi-demo/src/main/java/oshi/demo/WmiNoComInitQueryHandler.java

WMI performance improvement demo classes

---

.github/dependabot.yml
.github/workflows/ci.yaml
.github/workflows/coverity.yaml
.github/workflows/site.yaml
.github/workflows/sonar.yaml
.github/workflows/sonatype.yaml
.gitignore
.mvn/extensions.xml
.mvn/settings.xml

ubuntu jdk 15/16 seems to fail at least on initial push from my end.  Will come back to that later as it seems to be test differences.  Both the mac and windows seem ok there.
The remainder is setup of github actions matching at least where waffle is at.  For coverity, I'm not seeing oshi show up even though its configured so I have not added a secret for it yet and fully expect it to fail.

Github Actions introduction setup

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

Properly round Linux current frequency

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java
oshi-core/src/test/java/oshi/hardware/NetworksTest.java

Document unsigned int MTU and update toString

---

.github/workflows/ci.yaml
.github/workflows/coverity.yaml
.github/workflows/pr.yaml
.github/workflows/site.yaml
.github/workflows/sonar.yaml
.github/workflows/sonatype.yaml
CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

See https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-maven#caching-dependencies

Cache maven packages to speed up workflows

---

.cirrus.yml
.github/workflows/ci.yaml
.github/workflows/pr.yaml
CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdInternetProtocolStats.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/util/platform/unix/freebsd/BsdSysctlUtil.java
oshi-core/src/main/java/oshi/util/platform/unix/freebsd/ProcstatUtil.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java
oshi-core/src/test/java/oshi/util/ProcstatUtilTest.java

Fix FreeBSD test failures

---

.github/workflows/unixci.yaml
oshi-core/src/main/java/oshi/driver/unix/aix/Uptime.java
oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsNetworkIF.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOperatingSystem.java
oshi-core/src/test/java/oshi/software/os/FileSystemTest.java
pom.xml

Handle socket exceptions on NetworkIF instantiation

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSThread.java
oshi-core/src/main/java/oshi/util/platform/linux/ProcPath.java

Fetch thread names on Linux

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/Dmidecode.java
oshi-core/src/main/java/oshi/driver/linux/Lshal.java
oshi-core/src/main/java/oshi/driver/linux/Lshw.java
oshi-core/src/main/java/oshi/driver/linux/Sysfs.java
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32ComputerSystemProduct.java
oshi-core/src/main/java/oshi/hardware/ComputerSystem.java
oshi-core/src/main/java/oshi/hardware/common/AbstractComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsComputerSystem.java
oshi-core/src/test/java/oshi/hardware/ComputerSystemTest.java
oshi-demo/src/main/java/oshi/demo/ComputerID.java

Resolves #1474. 
Resolves and relates to #429, #581, neither of which should have been closed without doing this a long time ago.
Relates to #296, #693

Include ComputerSystem Hardware UUID

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/resources/oshi.architecture.properties

Parse Apple M1 Processor ID info

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacUsbDevice.java

Use IOUSB plane to iterate Mac USB controllers

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacUsbDevice.java

Continuation of addressing M1 problems in #1483

Use IOUSB plane to iterate/recurse Mac USB tree

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacBaseboard.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacFirmware.java

Apple M1 Baseboard and Firmware backups

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java

Addresses #1483 and improves on #1485

Bypass Rosetta for M1 architecture parsing

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/OSFileStore.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java

Report Linux filesystem label

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/resources/oshi.architecture.properties

Identify Rosetta as virtual architecture

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/PhysicalDisk.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsHWDiskStore.java

Fixes #1504 (and many earlier attempts to get this right)

Fix windows disk transfer time (yet again)

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacUsbDevice.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Get bare metal Apple M1 CPU info from IODeviceTree

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/util/FileSystemUtil.java
oshi-core/src/test/java/oshi/util/FileSystemUtilTest.java

Directly read M1 CPU IOPlatformDevice registry entries

---

oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/util/FileUtil.java

Document Linux RSS inaccuracy

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsHWDiskStore.java

Fixes #1521 
Regression introduced by #1307

Fix Windows partition GUID retrieval

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java

Fix Windows USB serial number retrieval

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java
oshi-core/src/test/java/oshi/util/FileSystemUtilTest.java
oshi-demo/src/main/java/oshi/demo/gui/ProcessPanel.java

Make process filtering and sorting more flexible

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Fix Windows version parsing regression

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java

Handle exceptions querying Windows user info

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java

Improved fallback logic to address #1558

Fallback to JVM filesystem size methods on native failures

---

oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessorInformation.java

Fix missing space in WMI process query

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java
oshi-core/src/main/java/oshi/jna/platform/windows/Kernel32Util.java

Fixes #1554 temporarily. Permanent fix tracked in https://github.com/java-native-access/jna/issues/1324

Handle new WinAPI Logical Processor Information types

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Handle empty process performance registry query

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java

Fix udev reference leak in LinuxNetworkIF

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/proc/CpuStat.java
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/software/common/AbstractOSProcess.java
oshi-core/src/main/java/oshi/software/common/AbstractOSThread.java
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/OSThread.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOSThread.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/test/java/oshi/hardware/CentralProcessorTest.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

Fixes #1586. Relates to #1583.

Add context switches to OSProcess

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/ThreadInformation.java
oshi-core/src/main/java/oshi/driver/windows/registry/ThreadPerformanceData.java
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSThread.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/main/resources/oshi.properties

Fixes #1581 by adding the SUSPENDED state for processes and threads.

Add suspended process and thread state for Windows

---

oshi-core/src/main/java/oshi/util/FileUtil.java

Log errors to debug when suppressed

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/wmi/MSFTStorage.java
oshi-core/src/main/java/oshi/driver/windows/wmi/OhmHardware.java
oshi-core/src/main/java/oshi/driver/windows/wmi/OhmSensor.java
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32DiskDrive.java
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32DiskDriveToDiskPartition.java
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32DiskPartition.java
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32LogicalDiskToPartition.java
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32PnPEntity.java
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32USBController.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsHWDiskStore.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsLogicalVolumeGroup.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsSensors.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsUsbDevice.java
oshi-core/src/main/java/oshi/util/platform/windows/WmiQueryHandler.java
oshi-demo/src/main/java/oshi/demo/UserComInit.java
oshi-demo/src/main/java/oshi/demo/WmiNoComInitQueryHandler.java

Single COM initialization for groups of queries

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/proc/ProcessStat.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java

An attempt to fix https://github.com/oshi/oshi/issues/1608

LinuxOSProcess#getOpenFiles returns one more than expected #1608

---

oshi-core/src/main/java/oshi/util/FileUtil.java

Reduce redundant property loading attempts

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java

Null check volume name when iterating Mac File Stores

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/NetworkIF.java
oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java
oshi-demo/src/main/java/oshi/demo/OshiGui.java
oshi-demo/src/main/java/oshi/demo/gui/InterfacePanel.java

Add getIndex() in NetworkIF and demo of Interfaces

Add getIndex() in NetworkIF and demo of Interfaces

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/mac/WindowInfo.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacHWDiskStore.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacPowerSource.java
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java
oshi-core/src/main/java/oshi/util/platform/mac/CFUtil.java

Null check all CFStrings to prevent exceptions

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdSensors.java
oshi-core/src/main/java/oshi/jna/platform/mac/SystemB.java
oshi-core/src/main/java/oshi/jna/platform/unix/NativeSizeTByReference.java
oshi-core/src/main/java/oshi/jna/platform/unix/freebsd/FreeBsdLibc.java
oshi-core/src/main/java/oshi/jna/platform/unix/openbsd/OpenBsdLibc.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOSProcess.java
oshi-core/src/main/java/oshi/util/platform/mac/SysctlUtil.java
oshi-core/src/main/java/oshi/util/platform/unix/freebsd/BsdSysctlUtil.java
oshi-core/src/main/java/oshi/util/platform/unix/openbsd/OpenBsdSysctlUtil.java

Fix macOS and unix sysctl mappings for size_t

---

pom.xml

Reverts oshi/oshi#1652
because of https://github.com/oshi/oshi/issues/1145#issuecomment-851026550

Revert "Bump maven-javadoc-plugin from 3.1.1 to 3.3.0"

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterQuery.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfDataUtil.java

PDH queries shouldn't be localized on Vista+

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterQuery.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterQueryHandler.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java

Fix PDH failed query thread safety

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessInformation.java
oshi-core/src/main/java/oshi/driver/windows/registry/ProcessPerformanceData.java

Fix WMI backup table source for process counters

---

CHANGELOG.md
UPGRADING.md
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Changed return type of getServices() to return a List

---

CHANGELOG.md
UPGRADING.md
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/driver/linux/DevicetreeTest.java
oshi-core/src/test/java/oshi/driver/linux/WhoTest.java

for #1727 
not sure if i understood it correctly, added two class DevicetreeTest.java and WhoTest.java

Added DevicetreeTest and WhoTest for Linux

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/DeviceTree.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsPowerSource.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java

Fix for the Issue - https://github.com/oshi/oshi/issues/1765

Fix Incorrect Use of Reference Equality for INVALID_HANDLE_VALUE

---

oshi-core/src/main/java/oshi/PlatformEnum.java
oshi-core/src/main/java/oshi/driver/unix/aix/PsInfo.java
oshi-core/src/main/java/oshi/driver/unix/solaris/PsInfo.java
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java

Please review this and merge if possible. Thank you!

Fix enums should be immutable by add the final modifier to enum fields

---

oshi-core/src/main/resources/oshi.architecture.properties

Update Microarchitecture table

---

.github/workflows/aix.yaml
.github/workflows/openbsd.yaml
.github/workflows/solaris.yaml

Limit concurrent workflow runs on the same server

---

pom.xml

Remove maven-scm-plugin and its dependencies

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxPowerSource.java
oshi-core/src/test/java/oshi/driver/linux/SysfsTest.java

Existing code only worked on Ubuntu.
Refactored to read from udev in the process.

Fix battery power usage rate on RHEL

---

CHANGELOG.md
FAQ.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterQueryHandler.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfDataUtil.java
oshi-core/src/main/resources/oshi.properties

Implement Processor Capacity to match Windows Task Manager CPU usage

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixHWDiskStore.java

Improved calculation of AIX disk reads and writes

---

.cirrus.yml
.travis.yml
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-dist/pom.xml
pom.xml

Easy way to get users to apply correct formatting regardless of how they edit files.

Add spotless-maven-plugin

---

pom.xml

Also just change to check instead of formatting

Move license check earlier in lifecycle

---

oshi-core-java11/pom.xml
oshi-core/pom.xml
oshi-demo/pom.xml
oshi-dist/pom.xml
pom.xml

Remove malformed DOCTYPE tag in POM files

---

oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java

Initial attempt to simplify calculations for #1936

Refactor processor utility calculations to reduce duplication

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java

Implementation in #1937 used wrong WMI field for elapsed time

Processor counter base is 100NS property

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/proc/Auxv.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxGlobalMemory.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/util/platform/linux/ProcPath.java
oshi-core/src/test/java/oshi/driver/linux/proc/AuxvTest.java

Get page size, clock ticks, and feature bits from Linux aux vector

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/proc/Auxv.java
oshi-core/src/main/java/oshi/driver/unix/aix/PsInfo.java
oshi-core/src/main/java/oshi/driver/unix/solaris/PsInfo.java
oshi-core/src/main/java/oshi/jna/platform/unix/AixLibc.java
oshi-core/src/main/java/oshi/jna/platform/unix/SolarisLibc.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOSThread.java
oshi-core/src/main/java/oshi/util/FileUtil.java
oshi-core/src/test/java/oshi/driver/unix/aix/PsInfoTest.java

Avoids the native memory reads/writes of the existing JNA struct approach

Refactor all binary file reading to use ByteBuffers

---

oshi-core/src/main/java/oshi/driver/windows/perfmon/ProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/resources/oshi.properties
oshi-core/src/test/java/oshi/driver/windows/perfmon/PerfmonDriversTest.java
src/site/markdown/FAQ.md

This should handle the final edge case.

Re-initialize utility counters if too much time has elapsed

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/unix/solaris/kstat/SystemPages.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisHWDiskStore.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisPowerSource.java
oshi-core/src/main/java/oshi/jna/platform/unix/Kstat2.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisFileSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/util/platform/unix/solaris/KstatUtil.java

Initial attempt to address #1934

Improve kstat chain locking

---

oshi-core/src/main/java/oshi/driver/unix/aix/Who.java
oshi-core/src/main/java/oshi/jna/platform/unix/Kstat2.java

Not used in OSHI (yet) but better mappings

Fix Kstat2 array mappings

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/test/java/oshi/SystemInfoTest.java

Show performance and efficiency core total on CPU toString

---

oshi-core/src/main/java/oshi/hardware/common/AbstractPowerSource.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxPowerSource.java

Don't show power supplies that aren't online

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/FileUtil.java

Pick one property file to load even with duplicates

---

oshi-core/src/main/java/oshi/software/os/OSFileStore.java

Add more detail to OSFileStore javadocs

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/test/java/oshi/SystemInfoTest.java

Include PID 0 on macOS

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java

Small but useful util methods to retrieve the current CPU usage easily.

Added getSystemCpuLoad/getProcessorCpuLoad convenience methods

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java

Prevent NPE when network interface has no statistics

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/common/AbstractOperatingSystem.java

Fix incomplete collection of child processes

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisPowerSource.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/util/GlobalConfig.java
oshi-core/src/main/java/oshi/util/platform/unix/solaris/KstatUtil.java
oshi-core/src/main/resources/oshi.properties

Implements code from #2068 for Kstat

Add a timeout for Solaris Kstat reads

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/platform/unix/solaris/KstatUtil.java

Revert "Add a timeout for Solaris Kstat2 reads"

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisPowerSource.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/util/GlobalConfig.java
oshi-core/src/main/java/oshi/util/platform/unix/solaris/KstatUtil.java
oshi-core/src/main/resources/oshi.properties

Reverts oshi/oshi#2070
Didn't solve the timeout problems. Probably need to investigate better locking.

Revert "Add a timeout for Solaris Kstat reads"

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/registry/HkeyPerformanceDataUtil.java

Reduce heap thrash with HKEY_PERFORMANCE_DATA buffer

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java

Fix processor numbering with Windows Processor Groups

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/jna/ByRef.java
oshi-core/src/main/java/oshi/jna/Struct.java
oshi-core/src/main/java/oshi/jna/platform/unix/FreeBsdLibc.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java

Proactively free native reference allocations on hot path

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/mac/net/NetStat.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdSensors.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java

Proactively free more ByReference allocations

---

oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

Changed private methods in LinuxCentralProcessor.java to static in oshi-core package

Fixed non-static private methods by making them private

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/util/platform/mac/SysctlUtil.java
oshi-core/src/main/resources/oshi.architecture.properties

Support Apple M2 chip

---

.github/workflows/solaris.yaml

This PR is for using vm actions in order to allow oshi its test case  in solaris,

Use vmactions GitHub action for solaris x86 test

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java

Properly determine Apple Silicon frequency

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxNetworkParams.java

Fix NPE for null canonical host name

---

CHANGELOG.md
oshi-core/src/test/java/oshi/driver/unix/NetStatTest.java
oshi-core/src/test/java/oshi/driver/unix/freebsd/WhoTest.java
oshi-core/src/test/java/oshi/driver/unix/freebsd/disk/DiskDriversTest.java
oshi-core/src/test/java/oshi/driver/unix/openbsd/disk/DisklabelTest.java

Update JUnit EnabledOnOS for OpenBSD and FreeBSD

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java
oshi-core/src/main/java/oshi/util/GlobalConfig.java
oshi-core/src/main/resources/oshi.properties

Suppress log warnings for non-root procfs reads

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/util/platform/linux/ProcPath.java

Better handling of ARM CPU Names

---

pom.xml

To remove unused imports:
https://github.com/oshi/oshi/pull/2204#issuecomment-1264560197

Enforce remove unused imports

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/openbsd/OpenBsdCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/platform/mac/SysctlUtil.java
oshi-core/src/test/java/oshi/SystemInfoTest.java
oshi-core/src/test/java/oshi/driver/windows/LogicalProcessorInformationTest.java

Add Processor Cache Information

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixCentralProcessor.java

Fix division by zero on AIX with fewer logProcs than physProcs

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/OSProcess.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOSProcess.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsFileSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

This resolves #2215 as it implements the second needed part.

Add process specific open file descriptor limits

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsInternetProtocolStats.java

Regression in 6.2.1 in #2081
Fixes #2242

Actually return Windows IP Connections

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixCentralProcessor.java

Fixes errors introduced in #2229

Ensure constant AIX processor tick count array

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/unix/aix/Lspv.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixHWDiskStore.java

Cache AIX partition list to reduce disk reads from lspv

---

CHANGELOG.md
oshi-core/src/main/java/oshi/jna/platform/linux/LinuxLibc.java
oshi-core/src/main/java/oshi/jna/platform/unix/AixLibc.java
oshi-core/src/main/java/oshi/jna/platform/unix/FreeBsdLibc.java
oshi-core/src/main/java/oshi/jna/platform/unix/OpenBsdLibc.java
oshi-core/src/main/java/oshi/jna/platform/unix/SolarisLibc.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSThread.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/aix/AixOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSThread.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOSThread.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/solaris/SolarisOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOperatingSystem.java
oshi-core/src/test/java/oshi/SystemInfoTest.java

Add getThreadId, getCurrentThread and getCurrentProcess to OperatingSystem API

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixCentralProcessor.java

Reverts #2258 and actually fixes it

Consistent treatment of AIX tick lengths

---

oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Discovered parsing issue on FreeBSD 13.1

Support CSV parsing generally and for FreeBSD cpu detection (#2309)

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java

Improve Udev exception handling

---

oshi-core/src/main/java/oshi/SystemInfo.java
oshi-core/src/main/java/oshi/driver/linux/Who.java
oshi-core/src/main/java/oshi/driver/mac/Who.java
oshi-core/src/main/java/oshi/driver/unix/freebsd/Who.java
oshi-core/src/main/java/oshi/driver/unix/solaris/Who.java
oshi-core/src/main/java/oshi/driver/windows/registry/ThreadPerformanceData.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisComputerSystem.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGlobalMemory.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/Util.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java
oshi-core/src/test/java/oshi/util/UtilTest.java

Refactored the code and also performed the suggestions provided by sonatype-lift. Haven't changed one suggestion as I wasn't sure if we can modify that or not as it was using the same logic priorly too.

Tried refactoring the code smells that I found while going through this project. #first-timers-only

---

oshi-core/src/main/java/oshi/driver/linux/Dmidecode.java
oshi-core/src/main/java/oshi/driver/linux/Lshw.java
oshi-core/src/main/java/oshi/software/os/OperatingSystem.java
oshi-core/src/main/java/oshi/util/UserGroupInfo.java

Skip Linux commands that require root if not elevated

---

pom.xml

Update maven git commit id plugin coordinates

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java

Graceful fallback for macOS Process user or group name

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java

Fix bit shifting in CPUID calculation

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

Add command-line fallbacks for udev and sysfs processor info

---

oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/unix/openbsd/OpenBsdCentralProcessor.java

Default max freq to max of current freq

---

CHANGELOG.md
oshi-demo/src/main/java/oshi/demo/ComputerID.java

Handle non-unique UUIDs in demo ComputerID class

---

README.md
src/site/markdown/FAQ.md

Fixes #2419 
Fixes #2409 
Also adds TOC to FAQ.
After merging, sync `site` branch to `main` and push upstream to update site docs.

Update FAQ for special Android dependency requirements

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/resources/oshi.architecture.properties

Lookup hardware implementer if lscpu fails to do so

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsCentralProcessor.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java

Fall back to vendor frequency on failed max on Windows

---

.github/workflows/linux.yaml
.github/workflows/macos.yaml
.github/workflows/pr.yaml

Java 21 is now released, no more ea, this should be enough to fix the build

Use Java 21 release

---

oshi-core/src/test/java/oshi/software/os/InternetProtocolStatsTest.java

Fixes [https://github.com/oshi/oshi/issues/2452](https://github.com/oshi/oshi/issues/2452)

Fix failing unit test on OpenBSD that broke due to InternetProtocolStats changes on Mac

---

oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/common/AbstractNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacGraphicsCard.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixGraphicsCard.java
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdPowerSource.java
oshi-core/src/main/java/oshi/hardware/platform/unix/solaris/SolarisCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsSensors.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacFileSystem.java
oshi-core/src/main/java/oshi/software/os/mac/MacOSProcess.java
oshi-core/src/main/java/oshi/software/os/mac/MacOperatingSystem.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/main/java/oshi/util/platform/windows/PerfCounterWildcardQuery.java
oshi-demo/src/main/java/oshi/demo/ComputerID.java
oshi-demo/src/main/java/oshi/demo/DetectVM.java
oshi-demo/src/main/java/oshi/demo/OshiHTTPServer.java
oshi-demo/src/main/java/oshi/demo/jmx/mbeans/Baseboard.java

defined locale in toUpperCase and toLowerCase methods

---

oshi-core/src/main/java/oshi/driver/unix/Who.java
oshi-core/src/main/java/oshi/driver/unix/aix/Who.java
oshi-core/src/main/java/oshi/hardware/common/AbstractUsbDevice.java
oshi-core/src/main/java/oshi/software/os/OSSession.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdOperatingSystem.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOSProcess.java
oshi-core/src/main/java/oshi/software/os/unix/openbsd/OpenBsdOperatingSystem.java
oshi-core/src/main/java/oshi/util/EdidUtil.java

defined locale for remainging toLowerCase toUpperCase and format method calls

---

.github/workflows/linux.yaml
.github/workflows/pr.yaml
oshi-demo/src/main/java/oshi/demo/gui/FileStorePanel.java
oshi-demo/src/main/java/oshi/demo/gui/MemoryPanel.java
oshi-demo/src/main/java/oshi/demo/gui/ProcessorPanel.java
oshi-demo/src/main/java/oshi/demo/jmx/mbeans/Baseboard.java
pom.xml

Part of #2451 
Note: will fail until other PRs fixing #2451 are merged. Leave open and re-run checks after rebasing to validate that the other PRs have fixed the issue.

Add forbiddenapis to enforce locale and other coding conventions

---

oshi-demo/src/main/java/oshi/demo/ComputerID.java
oshi-demo/src/main/java/oshi/demo/DetectVM.java
oshi-demo/src/main/java/oshi/demo/DiskStoreForPath.java
oshi-demo/src/main/java/oshi/demo/Json.java
oshi-demo/src/main/java/oshi/demo/UserComInit.java
oshi-demo/src/main/java/oshi/demo/annotation/SuppressForbidden.java
oshi-demo/src/main/java/oshi/demo/annotation/package-info.java
oshi-demo/src/main/java/oshi/demo/jmx/CreateJmxOshiAgent.java
oshi-demo/src/main/java/oshi/demo/jmx/JMXOshiAgentServer.java
oshi-demo/src/main/java/oshi/demo/jmx/demo/Client.java
pom.xml

Add system out suppression with exceptions for demo classes

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxPowerSource.java

Use sysfs as a backup for Linux power supply without udev

---

config/forbidden-apis.txt
oshi-core/src/main/java/oshi/hardware/platform/unix/freebsd/FreeBsdCentralProcessor.java
oshi-core/src/main/java/oshi/util/EdidUtil.java

forbid parse apis

---

.github/workflows/linux.yaml
.github/workflows/pr.yaml
README.md
pom.xml
src/site/markdown/index.md

Replace Coveralls with CodeCov

---

oshi-core/src/main/java/oshi/hardware/CentralProcessor.java

Fix NPE in ProcessorIdentifier edge case

---

.github/workflows/site.yaml

Add NVD API Key to Site workflow

---

.github/workflows/unix.yaml

Update for solaris-vm@v1

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractSensors.java

Remove unicode degree sign from output to improve portability

---

appveyor.yml

Use the maven wrapper with appveyor

---

oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/test/java/oshi/hardware/CentralProcessorTest.java

Fixes #2544 (or at least makes the edge case much more rare)

Improve calculations for Linux CPU max frequency

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/mac/MacCentralProcessor.java
oshi-core/src/main/resources/oshi.architecture.properties

Support Apple M3 chip

---

.github/workflows/macos.yaml
.github/workflows/pr.yaml

Add tests on Mac M1

---

.cirrus.yml
oshi-core/src/test/java/oshi/software/os/OperatingSystemTest.java

Adds working test for windows containers and fixes Linux ARM test

Update Cirrus CI config with more platforms

---

.github/workflows/coverity.yaml
.github/workflows/linux.yaml
.github/workflows/macos.yaml
.github/workflows/pr.yaml
.github/workflows/site.yaml
.github/workflows/sonar.yaml
.github/workflows/sonatype.yaml
.github/workflows/windows.yaml

The `setup-java` GitHub action has a built-in integration that completely replaces our existing cache setup.

Simplify cache setup

---

CHANGELOG.md
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java

Cache thread counters when updating OS Process with suspended state

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32PhysicalMemory.java
oshi-core/src/main/java/oshi/hardware/PhysicalMemory.java
oshi-core/src/main/java/oshi/hardware/common/AbstractGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGlobalMemory.java
oshi-core/src/test/java/oshi/hardware/GlobalMemoryTest.java

Add part number to Physical Memory for macOS, AIX

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/linux/Devicetree.java
oshi-core/src/main/java/oshi/driver/linux/Sysfs.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxHWDiskStore.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxLogicalVolumeGroup.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxNetworkIF.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxPowerSource.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java
oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java
oshi-core/src/main/java/oshi/util/Constants.java
oshi-core/src/main/java/oshi/util/GlobalConfig.java
oshi-core/src/main/java/oshi/util/platform/linux/DevPath.java
oshi-core/src/main/java/oshi/util/platform/linux/SysPath.java
oshi-core/src/main/resources/oshi.properties

Make sys and dev paths on Linux configurable

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGlobalMemory.java

Add more SMBIOSMemoryType values

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/wmi/Win32PhysicalMemory.java
oshi-core/src/main/java/oshi/hardware/PhysicalMemory.java
oshi-core/src/main/java/oshi/hardware/common/AbstractGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/mac/MacGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/unix/aix/AixGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGlobalMemory.java

new add physical memory of serial number

Add serial number to Physical Memory

---

CHANGELOG.md
oshi-core/src/main/java/oshi/jna/platform/windows/Kernel32.java
pom.xml

Update JNA dependency and remove (some) temporary code.

JNA 5.15.0

---

.github/renovate.json
pom.xml

Revert maven-site-plugin version

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/common/AbstractGlobalMemory.java
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java
oshi-core/src/main/java/oshi/util/ParseUtil.java
oshi-core/src/test/java/oshi/util/ParseUtilTest.java

Fixes #2792 
See https://github.com/mirror/dmidecode/blob/master/dmidecode.c#L2914

Support memory speed units of MT/s

---

CHANGELOG.md

Set the correct author information for the PR #2805 and #2814

Set the correct author information for the PR.

---

.cirrus.yml
.github/workflows/macos.yaml
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxCentralProcessor.java

Fixes broken CI and updates license headers using spotless

Misc fixes

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/perfmon/ThreadInformation.java
oshi-core/src/main/java/oshi/driver/windows/registry/ThreadPerformanceData.java
oshi-core/src/main/java/oshi/software/os/windows/WindowsOSProcess.java

Fix windows thread details collection

---

.github/workflows/site.yaml

using github token only, dropping ssh items.

Update site gha

---

CHANGELOG.md
oshi-core/src/main/java/oshi/driver/windows/LogicalProcessorInformation.java

Fix windows cache size

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java
oshi-core/src/main/resources/oshi.properties

Improve Linux temperature sensor selection

---

oshi-core/src/main/java/oshi/software/os/linux/LinuxFileSystem.java

Switch to DEBUG level for most file system errors

---

CHANGELOG.md
README.md
oshi-core/src/main/java/oshi/util/EdidUtil.java
oshi-core/src/test/java/oshi/util/EdidUtilTest.java

Added preferred resolution to the EDIDUtil class

Add preferred resolution to EDID Util

---

CHANGELOG.md
oshi-core/src/main/java/oshi/util/EdidUtil.java
oshi-core/src/test/java/oshi/util/EdidUtilTest.java

Added method to fetch monitor model in EDID Util

Add get monitor model to EdidUtil class

---

config/checkstyle-suppressions.xml
oshi-core-java11/src/main/java/module-info.java
oshi-core-java25/src/main/java/module-info.java
oshi-core-java25/src/main/java/oshi/ffm/mac/MacSystemFunctions.java
oshi-core-java25/src/main/java/oshi/ffm/mac/MacSystemHeaders.java
oshi-core-java25/src/main/java/oshi/ffm/mac/MacSystemStructs.java
oshi-core-java25/src/main/java/oshi/ffm/mac/package-info.java
oshi-core/src/main/java/oshi/hardware/platform/windows/WindowsGraphicsCard.java
oshi-core/src/main/java/oshi/software/os/mac/MacNetworkParams.java
oshi-core/src/main/java/oshi/software/os/unix/freebsd/FreeBsdNetworkParams.java

Fixed checkstyle errors, compiler warnings, and reduced log errors for no Mac domain name

Fix Miscellaneous warnings

---

oshi-core-java25/src/main/java/oshi/ffm/mac/MacSystemFunctions.java
oshi-core-java25/src/main/java/oshi/ffm/mac/MacSystemStructs.java
oshi-core-java25/src/main/java/oshi/software/os/mac/MacOSProcessFFM.java
oshi-core-java25/src/main/java/oshi/util/platform/mac/SysctlUtilFFM.java

Presently all MacOperatingSystem and MacOSProcess methods are migrated to FFM except for the initialization of Hz values using IOKit, which will be its own PR next...

Migrate MacOSProcess

---

oshi-core/src/main/java/oshi/util/FileUtil.java

Going back to closer to original implementation before #2969 but with better reader initialization

Restore partial file reading behavior

---

oshi-core/src/main/java/oshi/driver/windows/registry/InstalledAppsData.java
oshi-core/src/test/java/oshi/SystemInfoTest.java

Handle DWORD registry keys in Windows Installed Apps implementation

---

.github/workflows/coverity.yaml
.github/workflows/linux.yaml
.github/workflows/macos.yaml
.github/workflows/pr.yaml
.github/workflows/site.yaml
.github/workflows/sonar.yaml
.github/workflows/sonatype.yaml
.github/workflows/windows.yaml
README.md
oshi-core-java25/pom.xml
pom.xml

Updates java25 build profile and CI test matrices to Java 25

Build and test on JDK25

---

CHANGELOG.md
oshi-core/src/main/java/oshi/hardware/CentralProcessor.java
oshi-core/src/main/java/oshi/hardware/common/AbstractCentralProcessor.java

Add methods for calculating CPU usage with two arrays
